### ISSUE TITLE
enum34 should be required conditionally, only for Python < 3.4

### ISSUE THREAD

**Issue by lelit** [crossbario/crossbar#1146]
Currently crossbar installs enum34, a backport of Python 3.4 stdlib enum module to older snakes.

It should probably requires it only when running under such older versions of the interpreter, possibly using the [environment markers syntax](http://legacy.python.org/dev/peps/pep-0496/) (see also [this SO answer](http://stackoverflow.com/a/35614580/872328) for an example).

**Comment by meejah** [comment]
Since we use "hashin" to pin dependency hashes this requires some upstream support; I filed a PR: https://github.com/peterbe/hashin/pull/45

**Comment by oberstet** [comment]
Probably standard pip has gotten more features in the meantime too, and possibly we could switch over to pip (and skip hashin): https://pip.pypa.io/en/stable/reference/pip_hash/

_If_ that new pip also supports conditional, hashed dependencies - as we need to make this work ..

**Comment by karel-un** [comment]
As of crossbar 17.12.1 dependency on enum34 is still present when installing crossbar by pip on Python 3.6.

Uninstalling enum34 after installing crossbar and removing line with "enum34" from METADATA file fixes the problem.

**Comment by diefans** [comment]
how about https://pypi.org/project/enum-compat/

**Comment by FirefighterBlu3** [comment]
please change your `setup.py` reqs generation including `requirements-min.txt` so that things such as `enum34` and `ipaddress` are not pulled in as requirements for python > vX.Y. `setuptools` can use env markers so that install_requires can be generated like the following, see https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies for reference.

```
install_requires=[
    'enum34;python_version<"3.4"',
    'pywin32 >= 1.0;platform_system=="Windows"'
]
```

even when built in a docker image and/or venv, pulling in 3rd party modules on top of existing core modules usually breaks things. enum34 and ipaddress do this. additionally, several things like txtorcon really ought to be optional and a short printout should indicate "if you want to do FOO, also install python-foo"

**Comment by meejah** [comment]
Should be straightforward to use the version markers now that `hashin` supports this too..

**Comment by oberstet** [comment]
enum3.4 is removed from the dependencies on master: will be in crossbar 18.5.1. note: we will drop official support for python 2 with that version.
