### ISSUE TITLE
Unable to get CrossBar install working on Python 2.7.15 Windows

### ISSUE THREAD

**Issue by vnextcoder** [crossbario/crossbar#1366]
hi 

I just installed Python, Pip, and setuptools  on Windows 10 64Bit (version Microsoft Windows [Version 10.0.17134.165])

```
C:\> python --version   
Python 2.7.15

C:\> pip --version
pip 10.0.1 from c:\python27\lib\site-packages\pip (python 2.7)

C:\> crossbar version  
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\crossbar.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\crossbar\__init__.py", line 177, in run
    _personalities = personalities()
  File "c:\python27\lib\site-packages\crossbar\__init__.py", line 215, in personalities
    from crossbar import personality as standalone
  File "c:\python27\lib\site-packages\crossbar\personality.py", line 34, in <module>
    from collections.abc import Mapping
ImportError: No module named abc
```

The Crossbar is not able to get the collections.abc which I believe is only available in Python 3 . Can you please help

**Comment by Mdrbhatti** [comment]
According to #1332, python2 is no longer supported.

**Comment by om26er** [comment]
Closing this now, we are working to improve docs and will fix that soon.

**Comment by vnextcoder** [comment]
I moved to Python3.7 but now Twisted is failing. Twisted Docs say that they have Full Support only with Python 2.7 but CrossBar having only support 3.7.  it is becoming difficult for me to install CrossBar on my Windows 10 machine with Twisted install failing with similar errors as mentioned on Scrapy channel 
 https://github.com/scrapy/scrapy/issues/3322

Is there a workaround to get both Twisted and CrossBar working with Python 3.7 ?

**Comment by Mdrbhatti** [comment]
@vnextcoder You cannot build Twisted on Python 3.7 because VC++ compiler does not support it yet (only up to Python 3.6 I believe). https://wiki.python.org/moin/WindowsCompilers#Which_Microsoft_Visual_C.2B-.2B-_compiler_to_use_with_a_specific_Python_version_.3F

I had the same issue as you, and I got it working on Python 3.7 by installing pre-built binaries for Twisted here:
https://www.lfd.uci.edu/~gohlke/pythonlibs/#twisted

Twisted‑18.7.0‑cp37‑cp37m‑win32.whl should do the trick, You can install the .whl with pip.

Now when you install crossbar again, the Twisted dependency will be automatically resolved. Hope that helps!
