### ISSUE TITLE
Automate release to pypi

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar#1426]
Manual release process is tedious and repetitive and should be avoided to reduce human error. At the same time it will help us save time.

This issue only covers the automated release to pypi, this is a prerequisite for automated Docker images because our docker images install latest Crossbar from pypi.

**Comment by meejah** [comment]
The only "hard part" I can see is how to handle the signing key (for both the release artifacts, and signing the git tag). IMO, *ideally* we'd base everything off the git tag. That means: @oberstet signs a git tag and pushes it, and all else flow from there. So:

 - [ ] automate burning in the version from a git tag (versioneer, ...?)
 - [ ] how are the binaries themselves then signed?

**Comment by oberstet** [comment]
> because our docker images install latest Crossbar from pypi

whatever approach we take forward to automate docker image building, IMO it should

* allow to release docker images without pypi release
* also works for crossbarfx

> the build process for crossbarfx is using locally built wheels

so rather than binding our CD pipelines to pypi, IMO we need a way to realize more like this:

1. merge to **master** on any of our own repos builds the respective **Python wheel** and publishes/uploads it to our XX
2. new tag on any of our own repos does the same as 1., but _additionally_ publishes to pypi
3. all downstream artifacts like Docker images, snaps, EXE, .. are triggered and build from 1.

**Comment by oberstet** [comment]
see also: https://github.com/crossbario/crossbarfx/issues/99

**Comment by haizaar** [comment]
I highly miss this. So far I keep opening "Please version X tickets".

**Comment by om26er** [comment]
I think it has been discussed and agreed that we dont aant to automate releases.
