### ISSUE TITLE
Strange things happening on YIELD error

### ISSUE THREAD

**Issue by Jopie64** [crossbario/crossbar#1563]
Hello,

I'm working with WampSharp (backend) and autobahn.js (frontend) to connect to the crossbar router version cpy3-19.3.5 and ran into an issue when a progressive RPC was yielded from WampSharp. The router reported:

> YIELD received for non-pending request ID 180

After that it disconnected. There are 2 things I noted in this situation.

1. The client had multiple running progressive calls, but it looked like they didn't receive a response when the callee was thrown out. Hence the caller isn't aware of the callee not reacting any longer. On a normal disconnect, the caller does receive responses for the pending RPC's.
2. I traced back where Crossbar threw the callee out in the first place, and it looks like it is handling the YIELD of non-pending RPC as a protocol error:
https://github.com/crossbario/crossbar/blob/57a2393f62c32723b72cc9fcb5a26eb0a5365f57/crossbar/router/dealer.py#L1279
I think it should not handle a YIELD of a non-pending RPC as a protocol error because it can happen due to races. Warning about it is OK to me but killing the session is a bit rigorous I think.

But at least it should handle the disconnect gracefully.

**Comment by meejah** [comment]
How can it happen due to races? (and, if it does, that's a bug in one of the client libraries, likely or in crossbar itself)

Usually crossbar is fairly intolerant of protocol errors, because if a client has gotten to an illegal state, "guessing" what it'll do isn't good. In this case, for example, if it is sending a `YIELD` for a request that hasn't been issued, will it get "stuck" when (if?) the actual request comes through?

**Comment by Jopie64** [comment]
Example of a race:

- Consider a pending RPC
- Caller sends `CANCEL` with `killnowait`
- Dealer forwards it as `INTERRUPT` to callee, considers RPC done
- At the same time (before receiving `INTERRUPT`) callee sends `YIELD`
- `YIELD` is received while RPC is unknown by dealer

Still please also consider the first problem which is actually of bigger importance: the ungracefull disconnect of the callee without responding to the callees (who did nothing wrong) that the pending RPC's are cancelled.

**Comment by oberstet** [comment]
here is more discussion that might be relevant https://github.com/wamp-proto/wamp-proto/issues/160

**Comment by Jopie64** [comment]
Turns out the same problem occurs when callee reacts with `ERROR` on a cancel!

https://github.com/crossbario/crossbar/blob/cfa1feb938a7409ebae103649d1b47de29226101/crossbar/router/dealer.py#L1401

Scenario:
- Pending RPC is cancelled by caller (mode: 'kill')
- `INTERRUPT` is sent to callee
- Callee reacts with `ERROR` `wamp.error.cancelled` (or something similar)
- Router cannot find the pending RPC cause it is presumably already removed from dictionary. Reacts with ProtocolError, kills session and leaves pending caller RPC's to this session in the dark. Callers have no idea their RPC's will never complete.

This is double bad because:
1. Callee is allowed to react on `INTERRUPT` with `ERROR` even when router interrupted with mode `killnowait`. In this case the router should simply ignore the reply or pass it through to the caller depending on the mode.
2. The caller should know their RPC's are never gonna complete when the callee was killed due to protocol error.

**Comment by meejah** [comment]
I have been exploring this a little, I think the client-side should definitely be more "IETF" in its handling. That is, instead of aborting the connection on a (probably/possible) protocol error for these things (which definitely do have race-conditions we can't eliminate) it calls `.onUserError(ProtocolError(..))` -- where the default behavior is already just to log that.

Thus, if a client is very worried about strictness, they could choose to `self.abort()` (approximately) on any protocol-error by overriding `onUserError` .. but by default, connections won't die when this happens (which I feel is more in line with IETF "best effort" style anyway).

(I think there are also some things in crossbar that can improve the situation to avoid "it's a protocol error" more often, PRs incoming soon).

**Comment by oberstet** [comment]
I think a more relaxed behavior (ignoring replies that cannot be attached to an active request instead of bailing out) is coming via PR #1592 ..

**Comment by Jopie64** [comment]
@meejah Just wondering, how could the client want to behave differently on `.onUserError()` here? Cause  this is the router we're talking about... How would the client know it `misbehaved`?
