### ISSUE TITLE
Missing Realm Template Feature?

### ISSUE THREAD

**Issue by martindines** [crossbario/crossbar#1715]
Hi guys,

I am using Crossbar to handle communication between a single controller (client) and multiple servers (workers). Currently, I have defined a realm for each server (name: realm-<server_id>). The controller  connects to the server specific realm to communicate. This works as expected, but presents a scaling issue: With every new server added to the pool, a new realm needs to be added to the configuration.

While searching for solutions I stumbled across Realm Templates, demonstrated in the crossbar-examples repo (https://github.com/crossbario/crossbar-examples/tree/master/templates/realm-templates). This feature works by dynamically starting a realm when called. 

The Realm Templates feature does not appear to be included in the current codebase. The original implementation was done by @oberstet back in 2016 , included in PR https://github.com/crossbario/crossbar/pull/680 

Is there an alternative to Realm Templates that would allow realms to be created dynamically?

Thanks in advance!
Martin

**Comment by oberstet** [comment]
> The Realm Templates feature does not appear to be included in the current codebase.

"realm templates" was an experiment I did back then: the idea was allowing whole node configurations or at least realm configuration items be "templates" that would be fed dynamic data (eg realm name) and then "render" a config dynamically.

I stopped that experiment back then, because I didn't see how it wouldn't be "generic enough" and sustainable

> Is there an alternative to Realm Templates that would allow realms to be created dynamically?

yes, actually we have a super powerful feature: Crossbar.io actually has a WAMP-based management API built in that allows you to do _everything_ that can be done via node configurations - at run-time, without restarting the node and remotely.

it is also guaranteed to behave exactly the same as "static node configs" , because this management API is used internally always - also for static node configs.

---

the management API works like this:

* Crossbar.io _edge_ nodes open management connections to a Crossbar.io _master_ node
* the master node exposes a unified management API in turn, which then calls into the respective edge node management API - for any edge node connected

that way, you can manage all edge nodes from a single point of entry (the master node) - even if the edge nodes sit behind NATs or such!

the management API is built into Crossbar.io OSS, but to make use of it this requires our commercial, extended version: CrossbarFX

have a look at:

* https://crossbario.com/docs/crossbarfx/management/api/remote.html#router-workers
* https://crossbario.com/docs/crossbarfx/management/api/remote.html#crossbar.worker.router.RouterController.start_router_realm

here is an example how it is used. this dynamically starts a new router worker, realms, roles and transports on an edge node:

```python
@inlineCallbacks
def test_remote_router(cfx_master, cfx_edge1, realm_config=None, transport_config=None):

    mrealm = 'mrealm1'

    worker_id = 'worker1'
    worker_type = 'router'
    realm_id = 'realm1'
    transport_id = 'transport1'

    management_session, _ = yield functest_management_session(realm=mrealm)
    yield sleep(.1)

    # yield _prepare(management_session, mrealm)
    # yield sleep(.1)

    node_oids = yield management_session.call('crossbarfabriccenter.mrealm.get_nodes')
    assert node_oids
    node_id = node_oids[0]

    result = yield management_session.call('crossbarfabriccenter.remote.node.start_worker', node_id, worker_id, worker_type)
    print(hl(result, bold=True))
    yield sleep(.1)

    if not realm_config:
        realm_config = {
            "name": realm_id,
            "options": {
                "enable_meta_api": True,
                "bridge_meta_api": False
            },
            "roles": [{
                "name": "anonymous",
                "permissions": [{
                    "uri": "",
                    "match": "prefix",
                    "allow": {
                        "call": True,
                        "register": True,
                        "publish": True,
                        "subscribe": True
                    },
                    "disclose": {
                        "caller": False,
                        "publisher": False
                    },
                    "cache": True
                }]
            }]
        }

    result = yield management_session.call('crossbarfabriccenter.remote.router.start_router_realm', node_id, worker_id, realm_id, realm_config)
    print(hl(result, bold=True))
    yield sleep(.1)

    for role_config in realm_config.get('roles', []):
        role_id = str(uuid.uuid4())
        result = yield management_session.call('crossbarfabriccenter.remote.router.start_router_realm_role', node_id, worker_id, realm_id, role_id, role_config)
        print(hl(result, bold=True))

    if not transport_config:
        transport_config = {
            "type": "universal",
            "endpoint": {
                "type": "tcp",
                "port": 8080
            },
            "rawsocket": {},
            "websocket": {
                "ws": {
                    "type": "websocket"
                }
            },
            "web": {
                "paths": {
                    "/": {
                        "type": "nodeinfo"
                    }
                }
            }
        }

    result = yield management_session.call('crossbarfabriccenter.remote.router.start_router_transport', node_id, worker_id, transport_id, transport_config)
    print(hl(result, bold=True))
    yield sleep(.1)
```

**Comment by martindines** [comment]
Many thanks for your detailed response @oberstet ! I came across the Management API in a prior discussion but wasn't it how available (or stable) it was. I'll continue to research and let you know how I get on. Thanks for your hard work :-)

**Comment by oberstet** [comment]
we now also have orchestration via so-called web- and routerclusters where a master node manages a network of edge nodes .. that API is higher level than the remote node management API I described above (which is imperative, whereas the master node stuff is declarative)
