### ISSUE TITLE
crossbar and cloudflare

### ISSUE THREAD

**Issue by sgoudelis** [crossbario/crossbar#1731]
I am currently trying to use cloudflare in front of my crossbar router. The stack is as follows: 
Cloudflare -> nginx -> docker-proxy -> docker container running crossbar router. I have managed to get a message through to the crossbar router (dynamic authentication message) and I see that the dynamic authenticator RPC is responding to the request made. However, I am getting this message from the client that is requesting to be authenticated from crossbar:

```
Mar 24 09:41:33 buildroot python[2033]: 2020-03-24 09:41:33,475 INFO: connecting once using transport type "websocket" over endpoint "tcp"
Mar 24 09:41:34 buildroot python[2033]: 2020-03-24 09:41:34,135 ERROR: Session.onUserError(): "Authentication failed"
Mar 24 09:41:34 buildroot python[2033]: Traceback (most recent call last):
Mar 24 09:41:34 buildroot python[2033]:   File "usr/lib/python3.8/site-packages/txaio/aio.py", line 515, in done
Mar 24 09:41:34 buildroot python[2033]:   File "usr/lib/python3.8/site-packages/txaio/aio.py", line 427, in as_future
Mar 24 09:41:34 buildroot python[2033]:   File "usr/lib/python3.8/site-packages/autobahn/wamp/protocol.py", line 1779, in onChallenge
Mar 24 09:41:34 buildroot python[2033]:   File "usr/lib/python3.8/site-packages/autobahn/wamp/auth.py", line 187, in on_challenge
Mar 24 09:41:34 buildroot python[2033]:   File "usr/lib/python3.8/site-packages/autobahn/wamp/cryptosign.py", line 483, in sign_challenge
Mar 24 09:41:34 buildroot python[2033]: AssertionError: unexpected TLS transport channel ID length: was 48, but expected 32
Mar 24 09:41:34 buildroot python[2033]: 2020-03-24 09:41:34,141 INFO: session leaving 'wamp.error.cannot_authenticate'
Mar 24 09:41:34 buildroot python[2033]: 2020-03-24 09:41:34,144 INFO: left realm: unexpected TLS transport channel ID length: was 48, but expected 32 (session <autobahn.asyncio.wamp.Session object at 0x7f8836e1f0>)
Mar 24 09:41:34 buildroot python[2033]: 2020-03-24 09:41:34,151 ERROR: wamp.error.cannot_authenticate: unexpected TLS transport channel ID length: was 48, but expected 32
Mar 24 09:41:34 buildroot python[2033]: 2020-03-24 09:41:34,307 INFO: disconnected <autobahn.asyncio.wamp.Session object at 0x7f8836e1f0>, was_clean: True
```

Any ideas what is happening here?

**Comment by oberstet** [comment]
I can explain some pieces here .. but ultimately, this is strange Let me explain.

So apperantly, you're not only using TLS, but also a more complex setup in general (eg Cloudflare PoPs - which might do the initial TLS termination? - are on a IPv4 Anycast network as far as I know), but also WAMP-cryptosign authentication.

WAMP-cryptosign has a special protection feature against credential forwarding attacks:

>     Application-layer user authentication protocols are vulnerable to generic
    credential forwarding attacks, where an authentication credential sent by
    a client C to a server M may then be used by M to impersonate C at another
    server S. To prevent such credential forwarding attacks, modern authentication
    protocols rely on channel bindings. For example, WAMP-cryptosign can use
    the tls-unique channel identifier provided by the TLS layer to strongly bind
    authentication credentials to the underlying channel, so that a credential
    received on one TLS channel cannot be forwarded on another.

The assert fails

https://github.com/crossbario/autobahn-python/blob/7cb6f01d5e04310cc8c8df5a4fe6539e2ed69b87/autobahn/wamp/cryptosign.py#L483

because what is returned ultimately from here (for use of Autobahn as Crossbar.io does .. eg for dynamic authenticator run side-by-side with a router worker or inside a container worker at least)

https://github.com/crossbario/autobahn-python/blob/7cb6f01d5e04310cc8c8df5a4fe6539e2ed69b87/autobahn/twisted/util.py#L92

isn't 32 bytes.

And _that_ I don't understand how it can happen, because it returns `hashlib.sha256.digest` ..

**Comment by sgoudelis** [comment]
I just did another test excluding Cloudflare and the same error reproduces. I wonder if it is a good idea to do TLS termination on the crossbar router itself instead of the doing it in nginx. Any recommendations ?

**Comment by oberstet** [comment]
yes, I general our recommendation is to

* let the Crossbar.io router terminate TLS
* use TCP/IP layer 4 proxies/balancers (eg HAproxy)

I don't know if Nginx and/or Cloudflare can operate at pure L4 for websocket.

---

now, that being said:

1. WAMP-cryptosign should work on both TLS and non-TLS connections
2. WAMP-cryptosign should also work on connections that originate over TLS, but then are proxied to non-TLS to connect to crossbar
3. and it should work the same for a Twisted and asyncio based Autobahn client

relooking at the log you posted, I realize that you are actually trying to connect an AutobahnPython/asyncio WAMP client to Crossbar.io, and the error happens in the client?

also, to be sure: you terminate TLS at Nginx, and then talk non-secure websocket (no TLS) from Nginx to Crossbar.io?

---

depending on ^, there might be 2 bugs in AB here:

rgd 3., a difference between twisted and asyncio in how the TLS channel ID is computed:

* https://github.com/crossbario/autobahn-python/blob/7cb6f01d5e04310cc8c8df5a4fe6539e2ed69b87/autobahn/asyncio/util.py#L41
* https://github.com/crossbario/autobahn-python/blob/7cb6f01d5e04310cc8c8df5a4fe6539e2ed69b87/autobahn/twisted/util.py#L92

rgd 2.: when a connection originated over TLS at the client, the client will think it can/should use TLS channel binding. however, at the other end, crossbar receives a non-TLS connection (as the TLS has been terminated at the frontend proxy and forwarded non-secure) which does not allow to compute a TLS channel ID.

you could try overriding in `authextra` in your client

`'channel_binding': None`

instead of using

`'channel_binding': 'tls-unique'`

as eg in a client like this

https://github.com/crossbario/crossbar-examples/blob/master/authentication/cryptosign/static/client_raw_key_aio.py

This should completely disable channel binding and should practically solve the issue for your scenario.

---

Thinking more about this:

IMO _requiring_ the user to _actively_ disable TLS channel binding even though the connection is TLS is exactly right: the user should be aware that there now is a credential forwarding attack surface.

The TLS is not end-to-end (between the wamp client and router) anymore, and eg the proxy operator can forward credentials to somewhere else (rather the intended target crossbar) without the user noticing.

End-to-end TLS (between client and rouer) plus TLS channel bindings solves that.

**Comment by oberstet** [comment]
for reference, here are important RFCs rgd TLS channel bindings:

* https://tools.ietf.org/html/rfc5929
* https://tools.ietf.org/html/rfc5056

**Comment by sgoudelis** [comment]
Thank you very much for you comments Tobias. Yes I am TLS terminating on NGINX. I have not tried to TLS terminate on the crossbar router yet. I tried out the channel_binding switch to switch off channel binding on the client but the client connecting to the router produces this error message now:

```
2020-03-26 11:08:46,184 ERROR: Connection failed: ValueError: Unexpected key 'channel_binding' in 'authextra'
```

Looking at the code that triggers this error I see no mention of channel_binding option allowed there. Any clues about this ?


https://github.com/crossbario/autobahn-python/blob/7cb6f01d5e04310cc8c8df5a4fe6539e2ed69b87/autobahn/wamp/auth.py#L160

BTW my client code looks like this:
```
        extra = {
            # forward the client pubkey: this allows us to omit authid as
            # the router can identify us with the pubkey already => not true (MP)
            'pubkey': wamp_static_cryptosign_key.public_key(),
            'channel_binding': None
        }

        comp = Component(
            transports={
                'url': "/entrypoint"
                'serializers': [
                    'json',
                    'msgpack',
                    'cbor',
                    'ubjson',
                    'flatbuffers',
                ],
            },
            realm="myrealm",
            authentication={
                'cryptosign': {
                    'authextra': extra,
                    'authid': 'my@authid',
                    'authrole': 'role1',
                    'privkey': wamp_static_cryptosign_key._key.encode(encoder=HexEncoder),
                }
            },
            is_fatal=isfatal
        )
```

**Comment by sgoudelis** [comment]
Should I make an issue in the autobahn-python git page ?

**Comment by oberstet** [comment]
ok, so deactivating TLS channel binding is possible now for WAMP-cryptosign. here is a complete example https://github.com/crossbario/crossbar-examples/tree/master/authentication/cryptosign/tls

pls lemme know if that works for you on cloudflare/your setup ..

**Comment by sgoudelis** [comment]
@oberstet Thank you for your help. I just tried this and I it does not work for me. Please see my comment here: https://github.com/crossbario/autobahn-python/pull/1351

**Comment by oberstet** [comment]
@sgoudelis ahh, you seem to be using the new component API, not ApplicationSession? this attribute is indeed missing in https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/auth.py#L145 - that's a bug in component API (which is using authenticators) vs ApplicationSession (as it is used in the example ^, and which isn't using authenticators, but onChallenge callback)
