### ISSUE TITLE
How about an asyncio-based Crossbar for Python 3.3+ dev stacks?

### ISSUE THREAD

**Issue by emcd** [crossbario/crossbar#186]
As of this writing, Crossbar only works on Python 2.x because of an incomplete port of Twisted to Python 3. (I am still running into the twisted.systemd import issues on Python 3.{3,4} that others have mentioned in issue #41.) Seeing as Autobahn now has support for asyncio, which is available via Python stdlib in 3.4 and via a PyPI package in 3.3, I am wondering how much work it would be to create and maintain an asyncio-based code path in Crossbar.... Is this on your road map? I can understand that maintaining separate code paths (and maybe an abstraction layer) for two competing technologies might not be ideal... but, as of now, if I want to distribute a Python 3.3+ WAMP application with a WAMP router included, then it seems that I'm out of luck. (Unless I want to write my own Python 3.3+ WAMP router, which I really don't.)

I think that Autobahn has a lot going for it, providing both Python and Javascript libraries for WAMP, and I would love to be able to use it in my new projects. But, needing a WAMP broker that only runs on something outside of my dev stack is a bit of showstopper.

**Comment by oberstet** [comment]
As I stressed multiple times, Crossbar.io should be looked at as a blackbox. Users should not care about implementation details, like the language Crossbar.io is written in. Think RabbitMQ. It's written in Erlang. People don't seem to have problems with this, despite that most apps using RabbitMQ won't be written in Erlang.

**Comment by shulegaa** [comment]
False analogy?  

RabbitMQ is coded in Erlang, but, Erlang is declarative/functional.  The advantages attendant to that programming language do not (much) apply to software written in Python v2.7 (w/Twisted).  

Conversely, the concurrency challenges posed by Python v2.7 w/Twisted (e.g. Python's global interpreter lock - GIL - and so on) don't (much) apply to anything written in Erlang (e.g. RabbitMQ).  

In practice, web servers like Apache and Nginx are written in C/C++.  Same goes for databases like PostgreSQL, MySQL, etc.  Same goes for operating system kernels (like Linux).  Everybody knows that C/C++ is slow and hard to write well - especially compared to Python.  Still, those carefully and painfully crafted C/C++ code bases often work very, very well.  

While a WAMP 'router' implemented in Python v2.7 w/Twisted might be a convincing proof-of-concept (for WAMP), and while such a WAMP 'router' might also be a  great vehicle for shaking out WAMP design issues, it does not NECESSARILY follow that such a WAMP 'router' is generally appropriate for a demanding production deployment.  This seems like a legitimate question.   For putative users, this is a  timely question.

Users should care about implementation details - like the language Crossbar.io is written in.  There may, or may not, be relevant implications of this choice.  As much as I love coding in Python, either care about this choice, or blithely risk learning the hard way.  

Why risk yet more 'battle scars'?

**Comment by Paranaix** [comment]
> Everybody knows that C/C++ is slow

Im not sure where you got the idea that C++ or C is slow but its clearly wrong. You probably won't find any faster major language except maybe handcrafted and optimized assembler code.

**Comment by shulegaa** [comment]
Quite right!  C/C++ is slow to code.  C/C++ is even slower to code, debug, test and optimize **well**.  Still, and in general, C/C+ code is **NOT** slow to execute.  Mea culpa.  I misspoke.

C/C++ code tends to be about as fast as possible (... to execute).  Today, C is almost the new (portable, reasonably-well-optimized) 'assembler' language.  The overhead (and difficulty) of hand-crafting assembler is horribly high, these days.  It is getting worse and worse:

*  super-scalar instruction pipelining (instruction sequencing)
*  very-long-instruction-words (VLIW)
*  single-instruction-multiple-data (SIMD)
*  general-purpose-graphical-processing-unit (GPGPU) data-flow scheduling
*  etc.

As a practical matter, all of these complexities make manual 'assembler' coding an almost extinct art.  These days, compiler-support is almost mandatory for virtually any reasonably well-optimized X86 assembler (coding).  For the last two decades, it has become increasingly hard to cost-justify **any** hand-written assembler coding.

To agree twice over, when C/C++ is well coded, and then profiled, and then relentlessly tuned, it is all but impossible to beat compiled C/C++ code run-times.   

When it comes to this sort of C/C++ (memory-space and CPU-time) tuning, just rinse, lather and repeat.  Keep repeating - until some point of diminishing returns is reached.  

If you really want to wring (almost) out every last ounce of performance, and if cost (and time) is no object, then, just rinse, lather and repeat a lot.  Grind down the run-time.  

This is quite the opposite of my unfortunate mis-statement (above) - about C/C++ be 'slow' (in some unqualified sense).  That is, and was, both wrong and misleading.  I was typing too fast.  My apologies.  

C/C++ is only slow to code (well), slow to debug, slow to tune (well), etc.  Generally speaking, C/C++ is NOT slow to execute.

When coded well (with lots of time and attention), C/C++ tends to be about as fast as any other programming language could ever be.  

Sure, this is a sweeping generalization (and the Java/Scala/Clojure/JVM folks tend to jump all over this sort of overly general assertion).  The .NET CLR folks won't be far behind that first lynch mob.  There are some contrary corner-cases.  Sometimes, run-time feedback can tip the run-time (performance) advantages toward some JIT-compiled language - like Java/Scala/Clsoure/Jython or C#/F#/etc.  

While there can be some relatively unusual exceptions to the rule that C/C++ code is the 'fastest',  overall, C/C++ remains the fastest (to execute) in a general sense.  Redis is a good case in point.  This is one reason why folks like to cite the unreasonable effectiveness of C:

http://damienkatz.net/2013/01/the_unreasonable_effectiveness_of_c.html
http://damienkatz.net/2013/01/follow_up_to_the_unreasonable.html
https://news.ycombinator.com/item?id=8668680

Python is rarely even 1/2 as fast as corresponding C/C++.  That is true even for just-in-time compilers (JIT) like PyPy.  Lets not even discuss the lowest-common-denominator CPython (that most folks use to execute Python code).   This is why performance critical bits of python, like Numpy, are written in C (and then interfaced to Python/CPython).   

With Python's upcoming (not-yet-released) type hinting (enhanement), Python might more often get nearly 1/2 as fast as (corresponding) C/C++ code.  Even this will probably take some (future) new-fangled Python compiler, like clang, targetting the low-level-virtual-machine - LLVM.  It might take some JIT compiler technology, like (type-hinting-aware) PyPy (vNext).  Alternatively, it might take some other mechanism (like a type-hinting-aware Cython compiler).  For details on type hinting (in a Duck-typed, dynamically-typed language like Python), see PEP's 483 and 484:

https://www.python.org/dev/peps/pep-0483/
https://www.python.org/dev/peps/pep-0484/ 

Despite my misleading statement above, about C/C++ being 'slow' (in general), I was just trying to say that users should (and often do) care about implementation details.  The language used to implement Crossbar.io/Autobahn matters.  Run-time speed is one sort of reason.  Concurrency and scalability are other reasons.

As much as Python rocks, it still would be nice to know that somebody took the time, and invested the effort, to write (and optimize) a WAMP 'router' in C/C++.  

Even more ideally, it would be nice to know that the (executable) pseudo-code for such a WAMP 'router' started out as (pure) 'Python'.  Then, and as one plausible sign of WAMP 'router' maturity, it might be nice to see that some (relatively) painstaking, subsequent, C/C++ implementation (of some Python-based WAMP 'router' prototype) was done.  This last bit would be a most encouraging sign of WAMP's steadily increasing maturity.  This might become a sign of the 'WAMP' times.  From some, this might be recognized as a harbinger of a WAMP 'routers' production worthiness/readiness.  

I'm hardly volunteering to do all this work.  So - I cannot be complaining.  I am not complaining.
I am happy with whatever sort of  WAMP 'router' I can get for 'free' (as in beer and as in 'freedom').  Kudos to the crossbar.io team!

**Comment by hawkowl** [comment]
Since WAMP is an open standard, there are the possibility for other routers -- and in fact, there are! http://wamp.ws/implementations/#routers lists a few, in Java, Erlang, Lua, .NET, etc.

The biggest performance problem a WAMP router will face is not the router's processing performance itself, but how it handles being I/O bound. By definition, a WAMP router will spend most of its time passing though calls and waiting for responses, rather than doing any true "heavy lifting" itself. Twisted supports heavily I/O bound applications, like Crossbar.io, and running it on PyPy means that you can get within a factor of C's performance, which I think is perfectly reasonable.

**Comment by oberstet** [comment]
@shulegaa 

> it is all but impossible to beat compiled C/C++ code run-times. 

Not always. A *tracing* JIT (PyPy is one) can beat both non-profiled as well as profile-guided object code produced by C/C++ compilers. With a tracing JIT, your code is profiled and tuned at *run-time* to whichever load-profile your app will experience. Even using a profile-guided C/C++ compiler, your code is only tuned against that one profile used during compilation. When your production work load changes or does not fit the profile used for building, speed will go down.

I have written more C++ than Python in my life. In my opinion, it'll be hard to beat PyPy on WAMP routing using C/C++ for real world, networked load. Not impossible, but hard.

> The language used to implement Crossbar.io/Autobahn matters. Run-time speed is one sort of reason. Concurrency and scalability are other reasons.

Exactly. And another reason is security. And all are reasons why Crossbar.io is written in Python and uses Twisted.

**Comment by shulegaa** [comment]
Good point (oberstet) - and just as I said (above):  

"To agree twice over, when C/C++ is well coded, and then profiled, and then relentlessly tuned, it is all but impossible to beat compiled C/C++ code run-times."

I probably should have added the following, bold-faced word "JIT-tracing" to the following sentence (from my comment above).  I probably should have explicitly cited PyPy too:

"Sometimes, run-time **JIT-tracing** feedback can tip the run-time (performance) advantages toward some JIT-compiled language - like Java/Scala/Clsoure/Jython or C#/F#/etc **or PyPy** or whatever."

Skipping past latency, concurrency and scalability challenges (swirling around Python/PyPy), you bring up 'security' too.  Interesting!  Great topic.

Are you suggesting, or have you (already) tried, the newish PyPy sandboxing feature (for strong PyPy security)?

http://pypy.readthedocs.org/en/latest/sandbox.html

On the other hand, security is a very broad topic.  Security has to be designed into any program - written in any programming language.  Security is always hard to achieve.  The programming language itself is just on influence on the overall security profile/posture.  For example, the python ecosystem has the expected (normal and inevitable), drumbeat of security issues:

http://www.cvedetails.com/vulnerability-list/vendor_id-10210/Python.html

While Python itself, as a language, largely prevents at least one root cause of security vulnerabilities (the famed 'buffer overflow'), security is a 100x broader topic.  This is like one snowball on the tip of a (security-related) iceberg.  

Overall, security **is** quite a bit easier to achieve in Python than C (or C++), but security is not 'free' (nor automatic) just because Python (with Twisted) was used for the implementation (coding).  Here's are some concrete examples to consider:

http://www.exploit-db.com/exploits/35234/
https://blog.nelhage.com/2011/03/exploiting-pickle/
http://stackoverflow.com/questions/14588131/multiple-responses-in-twisted

I'll hasten to agree (once again) that Python programs are often about 10x easier to develop than equivalent programs in C (or C++).  This is especially true when some sufficient level of security is required.  

Writing secure network service programs, in Python, with Twisted, and with various Python imports/libraries supporting some of the best (and most secure) pythonic coding habits, might be around 20x easier than equivalent C/C++ programming.  As just one example (out of many), secure C/C++ programming tends to require static analyzers (aka lint-type tools like Coverity), memory usage profiling tools (like valgrind, Google's PerfTools, etc.)

http://valgrind.org/
https://code.google.com/p/gperftools/

I'm not trying to even appear argumentative.  I'm not suggesting that Python, and PyPy in particular, have not come a very long way in the last few years.  For example, this fluff piece (article) suggests that PyPy is now, in some general sense, about **6x** faster than CPython:

http://www.infoworld.com/article/2687086/python/pypy-powers-up-python.html
 
I get it.  With the type hinting slated for an near-term release of Python v3.x, Python (as a language) is becoming more and more suitable for an ever expanding range of applications.  Basically, Python is becoming suitable for almost any sort of application - well - short of operating systems, firmware, hard-real-time, etc.  I'm doubling down on my bet on Python's (increasingly) bright future.  Python is poised to take over (most) of the programming world ;-)  It has but few likely contenders - but that is another story for another day.   

It may already be the case that Python is more than 'good enough' for a production-grade WAMP router.  Still, this premise bears empirical, proof-in-the-pudding, testing.    

It seems especially dangerous to presume that a Python-based WAMP-router would escape from all security vulnerabilities, all the plausible (Python-related) scalability limits, all reliability concerns, all possible concurrency bottlenecks/limits (e.g. to presume it sidesteps all of the motivations for Python v3.4's asyncio), etc.  

Basically, end-users should care about what implementation language is used in any WAMP 'Router' they plan to put in production.  The implementation langauge alters the magnitude of the various risks they face.  The implementation language influences the priorities for empirical testing.  

The same should be said for any C/C++ based WAMP router that may or may not eventually emerge (in due course).  Any putative, future, C (or C++) based WAMP 'router' would need just as much empirical testing.  Here, end-users should care about C/C++ and the risks of buffer overflows, etc.
Given how much harder it is to code **well** in C/C++, maybe the need for empirical validation goes double for a putative C-based (or C++ based) WAMP router.  

In the end, one might guess that all the extra effort required for coding up a C/C++ based WAMP router might, in theory, lead to the best WAMP Router (in some general, multiple-aspect, sense).  Maybe.  Maybe not.  C (or C++) coding surely does not guarantee of that.  Conversely, neither does Python coding.  

There's often a gap between theory and reality.

One thing for sure, until the WAMP (v2?) **protocol** is stable (and also proven stable by way of real-world production applications), there is probably no way to cost-justify the **much** bigger effort required to implement a WAMP router in C/C++.  Until then, a WAMP 'router' in Python/Twisted might be optimal.

**Comment by oberstet** [comment]
@shulegaa "security" of course is a broad topic. We take security very serious. E.g. Autobahn pioneered strict UTF8 checking (we implement our own validation, since almost no language/run-time gets it right) and have created a WebSocket protocol testsuite "just" to test our WebSocket implementation - nowerdays used all over the industry (http://autobahn.ws/testsuite/#users)

**Comment by shulegaa** [comment]
Great stuff (on the UTF8 checker)!  More kudos to Crossbar.io/Autobahn.  Nice!  Thanks.

I might also suggest that the end-user interest in the implementation language might be mitigated by empirical (and reproducible) benchmarks.  This might be far easier than even contemplating the time/effort to implement a WAMP 'router' in any other programming language - like C/C++.  

If Python/Twisted implementation is (more than) 'good enough' (for many/most applications), then some empirical tests/benchmarks might quickly demonstrate that the implementation language choice is the moot point it was originally suggested to be.  From a practical standpoint, this might be sufficient for many, or most, prospective adopters ... like me ;-)  

Of course, I'm being greedy.  I'd love to have somebody else do the work I'll otherwise have to do myself!  But as you've just mentioned (in your last comment, oberstet), Crossbar.io's existing test/QA suites might already contain some grist along these lines.  I'd be forever grateful if you could share anything.  

One last point.  Since I have referenced C/C++ so often (in my comments above), I should probably point out that (the unreasonable effectiveness of) C might not be easy to carry over into C++.  

If (and that is a big 'if') anyone were to ever have a good reason to consider implementing yet another WAMP 'router', in either C or C++, then, there are some popular arguments for choosing C over C++ (... in at least some contexts/cases):

http://news.dice.com/2015/03/10/linus-torvalds-was-sorta-wrong-about-c/   
http://article.gmane.org/gmane.comp.version-control.git/57918

**Comment by emcd** [comment]
I thought this thread had died a couple of months ago. :)

Just to be clear, I hadn't intended it to be about the superiority or suitability of any language for any particular purpose. I've written plenty of Bourne Shell, C/C++, Fortran 77/90, Java, Mathematica, and Python 2/3 in my life and really don't have too many biases. The reason I asked the question about a Python 3.x solution was because I was looking for a simple, integrated solution that didn't require a potential contributor or user to install and configure additional dependencies by hand for development or trial purposes.

As I stated earlier, providing a "industrial grade" WAMP router (e.g., Crossbar.io) is fine by me. But, for someone to quickly be able to evaluate my project, I don't want them to have to install and configure such a thing separately. (All necessary parts should be able to provided via the setup script.) At one point, Autobahn had its own WAMP router included. When I originally looked at Autobahn for a Python 3-based project on which I am working, I noticed that the router code had moved to Crossbar.io. My initial hope was that @oberstet had planned on providing a Python 3.3+, asyncio flavor of Crossbar to meet my requirements. Failing that, I had hoped that maybe he had planned to reintroduce a lightweight version of the WAMP router back into the Autobahn code. Based on the response that I got, I am not sure that my question/argument was understood and I have decided to move on to work with other solutions....

In any case, this thread was not really intended to be about the language used to implement a standalone router. (Fun discussion though.) The real hope was for a lightweight router, which could be a simple dependency for a Python 3 project.

**Comment by sametmax** [comment]
The best way to get this is to : 

- Help porting twisted to Python 3 (https://twistedmatrix.com/trac/wiki/Plan/Python3). The port is currently stuck because of a lack of ressources. 
- Once it is ported, create a compatibility layer for twisted/asyncio.
- Integrate that to WAMP.
- Write a lib that allow you to start crossbar automatically in debug mode when you code your app.

You can see it's a lot of work, and it's why it's not priority since crossbar car be installed as a black box and you application code can be written already in asyncio.

But I agree with you, some kind of dev mode would be really nice and useful : you pip install, you start coding, and you'll think about prod later. It's just the amount of work is kinda freaky.

**Comment by oberstet** [comment]
Yes, FWIW, Crossbar.io will support running on Python 3 when Twisted does. Crossbar.io does not and will not expose a Python class level API, nor will it support asyncio as underlying network framework. The reason is that Crossbar.io should be considered a "black-box" router, not a Python library.

**Comment by emcd** [comment]
@oberstet, with all due respect, I think that you are misunderstanding the real issue that some of us keep mentioning. Please forget about the ticket title, forget about implementation language, and forget about asyncio for a little bit. The real issue is that several people are telling you that they would like to see a lightweight router either included as part of Autobahn (as it once was) or that they would like to see something like Crossbar able to be easily bundled and spun up from within their Python projects. Without this support, the barrier to entry for Autobahn/Crossbar is much higher than it could be. Removing the barrier to entry would likely attract more users to your software. IMO, you are making a strategic mistake that will impact the growth and adoption of this great product which you have created.

Obviously, this is your project and you can do with it what you want. Consider my comments to be friendly advice.

Now, as far as asyncio goes, the only reason I mentioned it is because it was an opportunity for me to avoid an additional dependency (Twisted) in the Python 3.3+ development stack. I have nothing much against Twisted. I do have something against extra dependencies.

Anyway, it doesn't look like Autobahn/Crossbar will meet my requirements at this point. Good luck with Autobahn/Crossbar, though.

**Comment by goeddea** [comment]
We see the issue. It's a question of resources and focus. The WAMP router in Autobahn|Python was there for historic reasons - otherwise clients and routers are separated. Considering the upcoming changes in architecture, having a basic router in Autobahn|Python and then building on this in Crossbar.io was no longer a good architectural choice. Leaving router functionality in Autobahn|Python would have meant maintaining two code paths. Without maintenance and extensions, the code in Autobahn|Python would not have provided what you want: a router which you can start development on to then move to something more performant for production.

**Comment by oberstet** [comment]
@emcd Here is how you can start Crossbar.io from Python:

```console
(python279_1)oberstet@thinkpad-t430s:~/scm/crossbar/crossbarexamples/rest/publisher$ ls -la
insgesamt 28
drwxrwxr-x 4 oberstet oberstet 4096 Mär 13 16:47 .
drwxrwxr-x 5 oberstet oberstet 4096 Mär 13 16:47 ..
drwxrwxr-x 2 oberstet oberstet 4096 Mär 13 16:48 .crossbar
-rw-rw-r-- 1 oberstet oberstet 2196 Mär 13 16:47 publish.py
-rw-rw-r-- 1 oberstet oberstet 2127 Mär 13 16:47 publish_signed.py
-rw-rw-r-- 1 oberstet oberstet  924 Mär 13 16:47 README.md
drwxrwxr-x 2 oberstet oberstet 4096 Mär 13 16:47 web
(python279_1)oberstet@thinkpad-t430s:~/scm/crossbar/crossbarexamples/rest/publisher$ python
Python 2.7.9 (default, Jan 18 2015, 21:40:29) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.system("crossbar start")
Stale Crossbar.io PID file /home/oberstet/scm/crossbar/crossbarexamples/rest/publisher/.crossbar/node.pid (pointing to non-existing process with PID 21983) removed
2015-03-13 16:48:34+0100 [Controller  22070] Log opened.
2015-03-13 16:48:34+0100 [Controller  22070] ==================== Crossbar.io ====================
	
2015-03-13 16:48:34+0100 [Controller  22070] Crossbar.io 0.10.2 starting
2015-03-13 16:48:34+0100 [Controller  22070] Running on CPython using EPollReactor reactor
2015-03-13 16:48:34+0100 [Controller  22070] Starting from node directory /home/oberstet/scm/crossbar/crossbarexamples/rest/publisher/.crossbar
2015-03-13 16:48:34+0100 [Controller  22070] Starting from local configuration '/home/oberstet/scm/crossbar/crossbarexamples/rest/publisher/.crossbar/config.json'
2015-03-13 16:48:34+0100 [Controller  22070] Warning, could not set process title (setproctitle not installed)
2015-03-13 16:48:34+0100 [Controller  22070] Router created for realm 'crossbar'
2015-03-13 16:48:34+0100 [Controller  22070] No WAMPlets detected in enviroment.
2015-03-13 16:48:34+0100 [Controller  22070] Starting Router with ID 'worker1' ..
2015-03-13 16:48:34+0100 [Controller  22070] Entering reactor event loop ...
2015-03-13 16:48:34+0100 [Router      22079] Log opened.
2015-03-13 16:48:34+0100 [Router      22079] Warning: could not set worker process title (setproctitle not installed)
2015-03-13 16:48:35+0100 [Router      22079] Running under CPython using EPollReactor reactor
2015-03-13 16:48:35+0100 [Router      22079] Entering event loop ..
2015-03-13 16:48:35+0100 [Controller  22070] Router with ID 'worker1' and PID 22079 started
2015-03-13 16:48:35+0100 [Controller  22070] Router 'worker1': realm 'realm1' started
2015-03-13 16:48:35+0100 [Controller  22070] Router 'worker1': role 'role1' started on realm 'realm1'
2015-03-13 16:48:35+0100 [Router      22079] Site starting on 8080
2015-03-13 16:48:35+0100 [Controller  22070] Router 'worker1': transport 'transport1' started
```

**Comment by emcd** [comment]
@goeddea: Yes, you understand the issue. Thank you. And, yes, I realized that code maintainability could be a problem (and mentioned this in my OP). Right now, you are making a trade-off between architecture and user (developer) experience - favoring architecture. One possibility might be to factor out the bare essential router code into a separate, common package and let that package be a dependency of both Autobahn|Python and Crossbar.io. (Basing it off of asyncio might be a good choice, because trollius provides compatibility for Python 2.{6,7}, whereas Twisted is not ready for Python 3.x yet.) Another benefit of factoring out the bare essential router code would be that it could enable easier porting to other development toolchains, such as Ruby or Node.js. And, that would make your product more competitive with Meteor.js DDP by allowing other toolchains to easily deploy and spin up WAMP routers without needing to install your Python-based WAMP router separately. (Same issue as I have raised, but for other dev stacks outside of Python.)

@oberstet: Yes, there are a number of ways to do fork-exec or popen from Python. (I personally prefer subprocess.Popen for most cases.) And, I'm not concerned about that. The problem is that when someone runs a distutils- or setuptools-based setup.py, the dependencies, which are fetched, are relative to the version of Python that is running the script. If the required version of Python for Crossbar.io is incompatible with the required version of Python for the software being installed, then that is problematic.

I find Autobahn to be highly compelling because of the Python and JS implementations both being supported by the same developers - and because it provides the functionality that I want on a dev stack with which I am comfortable. Unfortunately, it is not in a form that I can easily use right now. But, this is your project and your decisions to make. I wish you success in your development of the project.

**Comment by oberstet** [comment]
@emcd So your actual pain is that Crossbar.io currently does not run on Python 3? Since if it would, you could add Crossbar.io as a simple dependency in your `setup.py` and start it from without your program?

**Comment by emcd** [comment]
@oberstet That is the essence of the problem. Which is why I suggested making a version of Crossbar.io which is not tied to a dependency (Twisted) that is currently holding you down to Python 2.x.

Yes, having a Python 3 version of Crossbar.io would be a good start. I (and other developers) could then write the necessary logic to configure a router for the first time and thereafter start it as necessary. But, if you really wanted to make life easy for developers, then you could provide this logic as an extra feature of Autobahn|Python. For example, Pyro (a Python RPC library) provides such functionality for its name server: http://pythonhosted.org//Pyro4/nameserver.html#starting-the-name-server-from-within-your-own-code . The Erlang WAMP library seems to provide this as well: https://github.com/bwegh/erwa#router .

**Comment by oberstet** [comment]
@emcd The solution for Python 3 is to finish Twisted support for Python 3, not removing Twisted, which would mean we'd need to write a lot of stuff ourselves or introduce other dependencies. You will then be able to include Crossbar.io in any Python project (Python 2 or 3) as a dependency and configure and start Crossbar.io from within the app. I fail to see how copying code to AutobahnPython would improve that further.

**Comment by shulegaa** [comment]
Stray thought, would trollius (asyncio for Python 2.7) be of any potential help?  Just wondering.  I'm not at all sure this is applicable.  Maybe the point isn't Python 2.x and Python 3.x 'same source' support (ala six), but rather retention of Twisted (and thus minimization of existing code base changes).  

http://trollius.readthedocs.org/

**Comment by oberstet** [comment]
@shulegaa Nope, this won't help. That's what we do with AutobahnPython btw.

FWIW, I have opened https://github.com/crossbario/crossbar/issues/268
