### ISSUE TITLE
rlinks: duplicate events after reconnect

### ISSUE THREAD

**Issue by asimfarooq5** [crossbario/crossbar#1916]
If the connection between instance A and B is lost, On connection resume/resubscribe the event causes duplicate results for number of times it reconnects.

The same configuration can be used to reproduce the bug #1909  

* Start both Instances A and B
* Subscribe event on instance A and B
* Publish event to instance A and B
* get the same event on both instances
* stop/restart instance B then resubscribe
* Now, when the event is published to instance A, this will result in duplicate events on instance B

**Comment by om26er** [comment]
This issue is real, I can reproduce that. It seems the local leg has the registrations even when the remote end disconnected/stopped. In such event the following code is not called https://github.com/crossbario/crossbar/blob/01ec53a100b08a4b78adabe26ab0abb12ba21d5a/crossbar/worker/rlink.py#L167

So we probably need to update `on_remote_leave` to unsubscribe to the remote events https://github.com/crossbario/crossbar/blob/01ec53a100b08a4b78adabe26ab0abb12ba21d5a/crossbar/worker/rlink.py#L204

**Comment by oberstet** [comment]
As a note, it can be daunting/confusing to think about and keep all message interactions for a certain scenario  in mind with this rlink stuff. In particular, since those WAMP messages happen at the meta level, and at the app level.

* pls consider https://github.com/crossbario/crossbar/blob/master/docs-cfx/_static/crossbar-rlinks.pdf - I tried to make this stuff approachable, and ..
* This is supposed to intro one graphical notation for documenting what is supposed to happen with rlinks at the WAMP message level in an accurate way.
* If that notation makes sense and is welcome, we could add all message interactions and scenarios

**Comment by asimfarooq5** [comment]
It seems to be fixed with proposed branch #1919.
