### ISSUE TITLE
little feature: add a CLI command: "crossbar stop"

### ISSUE THREAD

**Issue by markope** [crossbario/crossbar#201]
When developing I frequently start the crossbar node from the crossbar directory using
`crossbar start` to conveniently see the log output. It would be nice to be able to call `crossbar stop` in the same fashion from the node folder.

I guess it would be enough to put a crossbar.pid file into the .crossbar folder upon start to get access to the crossbar process to kill.

**Comment by ubriaco** [comment]
It would be a very useful feature. <code>crossbar restart</code> is also needed (sometimes i need to reload config).

**Comment by oberstet** [comment]
* depends on #52 
* restrictions apply: on Windows, process signals are unsupported, which means, Crossbar.io can only be "killed", not shutdown orderly (which isn't a real problem ..)
* `crossbar restart` is yet another thing, since it requires to start a new process *with the same command line arguments*

**Comment by oberstet** [comment]
Ok. The Crossbar.io CLI now has 3 new commands:

*  `stop`
*  `status`
*  `restart`
