### ISSUE TITLE
create multi-platform docker images to more easily work in multiple architectures

### ISSUE THREAD

**Issue by markope** [crossbario/crossbar#2057]
I don't know your build pipeline, but it should be a fairly simple addition. Something like

```
docker buildx build --push \
--platform linux/amd64,linux/arm64 \
--tag crossbario/crossbar:v22.2.2 .
```

should do it.

On dockerhub this then should look like 
<img width="625" alt="image" src="https://user-images.githubusercontent.com/1944925/198652122-91f9821a-327e-42ee-b684-0168a2a9f323.png">

**Comment by markope** [comment]
If you give me a pointer to the repo for the docker image creation I could try to prepare a PR. The links in the dockerhub documentation are broken. e.g. https://github.com/crossbario/crossbar-docker#running

**Comment by oberstet** [comment]
> I don't know your build pipeline

there is no build pipeline for docker images in this repo

**Comment by markope** [comment]
but where is it ?

**Comment by oberstet** [comment]
> but where is it ?

it's in a private repo, and it includes arm64 image building (but not the elegant new "buildx" stuff you pointed to), but it isn't yet fully "cloud-CI automated". historically, this was too cumbersome anyways, since the image building broke every 2nd release;) however, lately, that's not the case as often anymore, and the main pain is now the time it consumes my notebook since the image building is automated but to cloud-CI automatic.
