### ISSUE TITLE
Make it possible to pass WAMP packets "by reference" instead of "by value"

### ISSUE THREAD

**Issue by Emasoft** [crossbario/crossbar#217]
Make it possible to pass WAMP packets "by reference" instead of "by value". Currently the data shared between nodes or modules of an application are passed around in WAMP packets that are duplicated many time (one for each node using it), wasting a lot of memory. Please make it possible to just publish a packet on crossbar, and then just pass the reference to it afterward. This will reduce the memory footprint and will allow a better integration between plugins and components using WAMP API.

**Comment by oberstet** [comment]
You probably want GC then with distributed object references as well. In which case you need distributed GC also. Which is kind a challenge ...

Am 23.01.2015 20:26 schrieb Emasoft <notifications@github.com>:

Make it possible to pass WAMP packets "by reference" instead of "by value". Currently the data shared between nodes or modules of an application are passed around in WAMP packets that are duplicated many time (one for each node using it), wasting a lot of memory. Please make it possible to just publish a packet on crossbar, and then just pass the reference to it afterward. This will reduce the memory footprint and will allow a better integration between plugins and components using WAMP API.

**Comment by Emasoft** [comment]
@oberstet : no need to create a distributed GC. You just need to have the shared memory unit managed by the wamp router (see the graph below) and the router would mantain a reference counter of all nodes with "registered" wamp packets. When a wamp packet has no more active registered nodes, then it can be garbage collected. It's more predictable and easy than GC, because wamp nodes need to explicitly ask for storing a packet in the router. Not all packets need to be of "reference type". Only big packets with lots of data (i.e. bitmaps, documents, data tables from sql, etc.) that need to be accessed by many wamp nodes or modules of the app at the same time, and that would be slow and bloated to duplicate those in each node passing them "by value".   
![unified_routing_wamp_iot_proposal_shared_memory_](https://cloud.githubusercontent.com/assets/713559/5883808/06437886-a356-11e4-8451-503d65c77370.png)

**Comment by oberstet** [comment]
We will soon have distributed Crossbar.io nodes, so we would need distributed GC. Anyway: WAMP is a messaging system, not at shared memory system.
