### ISSUE TITLE
Clarify AGPL and WAMP app components

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#224]
We should clarify our position on AGPL and WAMP application components (what is considered a "separate" work and what is considered a "dervied work" from our point of view) similar to what MongoDB does:

> To make the above practical, we promise that your client application which uses the database is a separate work. To facilitate this, the mongodb.org supported drivers (the part you link with your application) are released under Apache license, which is copyleft free.
Note: if you would like a signed letter asserting the above promise please contact MongoDB, Inc.

See: http://stackoverflow.com/questions/28198158/clarification-of-the-license-conditions-of-crossbario/28203511

**Comment by goeddea** [comment]
Clarified this in

* the license file
* the FAQ
* a documentation page

**Comment by rnixx** [comment]
With full respect to the decision already made to license AGPL and to the argument that router and application code should not be mixed (I've read this in some thread). I'd really like to run crossbar in the same process as my application runs, just because of system setup complexity and maintainance reasons. I cannot publish parts of this application, so AGPL becomes a no-go. What prevents you to license LGPL, which also forces changes in crossbar to be published and gives the user a more liberal license?

Thanks for your patience
