### ISSUE TITLE
Crossbar.io Programming Guide

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#230]
> "Crossbar.io Programming Guide"
> 
> Covering programming with Crossbar.io, Python and JavaScript in the
> browser and Node.
> 
> Currently, the only docs are
> 
> http://autobahn.ws/js/programming.html
> http://autobahn.ws/python/wamp/programming.html
> https://github.com/crossbario/crossbar/wiki/Programming
> 
> But these are very terse, not tailored to Crossbar.io and do not
> provide a lot of "hands-on" examples and code idioms.
> 
> With the latter I mean this (which I started long ago .. is partially
> outdated etc, but just to illustrate):
> 
> https://github.com/tavendo/AutobahnPython/blob/master/doc/work/programming.rst#batching-calls
> 
> Usually, when I forgot about how to use some feature, I steal from
> 
> https://github.com/tavendo/AutobahnPython/tree/master/examples/twisted/wamp/basic
> 
> Which essentially contains "idioms", but without any explanation. It
> would be awesome to have a "programming guide" with all those info and
> idioms consolidated.
> 
> That guide should be part of the Crossbar.io docs:
> 
> https://github.com/crossbario/crossbar/wiki/Programming-Guide
> 
> Larger/complete examples should reside in:
> 
> https://github.com/crossbario/crossbarexamples

**Comment by Vayel** [comment]
I would help for it but I don't unserstand what it aims at exactly. Would do have a TOC?

**Comment by goeddea** [comment]
Thanks for continuing with your input!

What we want is to have tutorials for common tasks (e.g. authorization) and common patterns (e.g. I often publish an event based on an RPC, and exclude the caller from receiving the event). 

The idea is that a user with a common problem finds something which covers this and gets code which he can hack to implement his own solution. For simpler things, the code should be executable. Not all of it needs to be covered in the tutorial itself - we can link to code in the crossbarexamples repo. For more complicated things, e.g. architectural questions, we might have just diagrams.

Examples with code should ideally always include JavaScript (since this is fast becoming the lingua franca of programming), and probably Python. We ourselves work mostly in JavaScript & Python, but in an ideal world, every example would contain code for all the languages with WAMP libraries which support the features needed for implementing the example (not that this is likely to happen, but the more languages the higher the probability that somebody looking will find code that's easy to read for him or her).

We don't have a TOC for the guide, but some topics which have come up repeatedly on the mailing lists are:

* authorization methods & how to combine them with existing infrastructure
* getting & handling caller identity in callees/across application components
* using promises (which is a topic of its own, really, but some examples in connection with Crossbar.io/WAMP would be nice)

Otherwise: Anything you've come across during your usage of Crossbar.io which the documentation did not solve for you is a candidate. 

I suggest we start a wiki page for this suggestions here in this repo so that we can coordinate and don't have overlap in our efforts.

Once again: Thanks for helping us in making Crossbar.io better and more accessible!

**Comment by Paranaix** [comment]
> JavaScript (since this is fast becoming the lingua franca of programming)

I doubt that. Just because something becomes hyped and is in vogue (while the extent is doubtable as well) doesn't mean it will last for long.

There should definitely be a section covering serialization and deserialization (i.e what types are accepted, in what do they get transformed, how to implement serialization for custom user types).

**Comment by Vayel** [comment]
Ok, thanks! What I projected to do is more related to AutobahnPython then:

* What does `inlineCallbacks`?
* How to call a procedure from another RPC procedure (chain calls)?
* Can I call a method via `self.method` even if it is registered as a procedure?
* ...

Is Crossbar Web site to introduce to code?

@Paranaix : I don't agree with you about JS. I do think it is an easily-readable language. For example, AutobahnPython codes use `inlineCallbacks` and generators, which make the code harder to understand.

+1 for serialization.

**Comment by goeddea** [comment]
I didn't intend to start a flame war on the topic of programming languages. ;) I just think that JavaScript is something that more people come into contact with than with other languages - which has to do with it being in vogue. No value judgement here.

I've started a wiki page in the [crossbarwww repo](https://github.com/crossbario/crossbarwww/wiki/Programming-Guide) and added your suggestion regarding serialization.

**Comment by Paranaix** [comment]
There is no need to cover the @inlineCallbacks or @coroutine decorator as it is not part of Autobahn. Its merely something for convenience and originates from twister or asyncio. Both already have in-depth documentation about asynchronous programming and those decorators in particular. If the decorator is used in examples, it should be introduced with a single sentence and then refer to the official twistar/asyncio documentation.

**Comment by goeddea** [comment]
@Vayel - The topics you mention are indeed more specific to AutobahnPython, and should probably be part of the the documentation there. While Paranaix is right that these are not specific to Autobahn, there's no reason not to have a brief explanation of the concepts as they are needed to understand example code.

**Comment by goeddea** [comment]
reopening (was moved to https://github.com/crossbario/crossbardocs/issues/21 and is now back here)

**Comment by oberstet** [comment]
We now have a programming guide for CB here https://crossbar.io/docs/Programming-Guide/ and also the AB docs have been improved massively https://autobahn.readthedocs.io/
