### ISSUE TITLE
Creating a repo for the wiki

### ISSUE THREAD

**Issue by Vayel** [crossbario/crossbar#246]
[Creating a repo](http://nerds.investigativenewsnetwork.org/2014/05/19/applying-git-to-github-wikis/) for the wiki would enable us to:

* open issues
* send pull requests

Thanks.

**Comment by oberstet** [comment]
Those are valid advantages. Currently, the build for the Web site (where the docs are hosted) is from the Wiki pages to `crossbarwww`. We might think about moving the docs markdown files simply to `crossbarwww`. We would loose the nice Wiki editing though.

**Comment by Vayel** [comment]
A few more aguments then:

* No longer need to clone the wiki to install the Web site locally
* Only one place for the documentation
* `crossbarwww` ≈ server hosting `crossbar.io`

**Comment by goeddea** [comment]
Wherever it lives, we want the documentation to be in markdown, and generate HTML from that.

Writing and maintaining documentation in HTML is to much work. With markdown we have a simple syntax for simple things, and can still embed HTML when needed for something fancy.

**Comment by Vayel** [comment]
I agree. The third point means that the structure of the repo would be almost the same as the one on the prod server. Today, we wonder where the docs are when we look at `crossbarwww`.

**Comment by goeddea** [comment]
With the present structure, anybody can edit the documentation online without the need for any downloads etc. I think this is a huge advantage - but needs to be communicated in the deployed documentation (link to the wiki page on each page). We ourselves will often just edit the wiki online instead, especially since this offers easy preview of the rendered content.

One confusing thing is that the Web site repo does not contain the documentation files. 
My question is how likely people are to want to deploy the Web site themselves, and then stumble over the requirement to have the wiki repo locally as well (which is documented). 
My feeling is that this is a borderline use case. 

What I do think is a valid concern is that documentation issues cannot be closed via commits to the wiki repo (at least not that I've found a possibility yet). GitHub does not seem to process commit messages the same here as it does for the "real" repos. 

My feeling is that the being able to edit online outweighs solving this problem for the time being. 

I vote to close this is issue for now.

**Comment by Vayel** [comment]
What should I do if I have suggestions to improve the wiki but don't want to edit it without discussion? Should I open an issue in `crossbarwww`?

**Comment by goeddea** [comment]
Good question. 

Since the wiki is part of the CB repo, we ourselves have traditionally filed issues in the crossbar repo itself, and tagged them with "documentation".

I'd suggest doing the same, since this makes it easier to get an overview of the documentation.

If somebody files an issue with the crossbarwww repo, then that's not a problem - it's just not how we usually do things.

And, by the way, keep filing issues! It's really helpful to us.

**Comment by Vayel** [comment]
What about using the wiki of `crossbarwww` in order to have the docs on one place and let the issues of that repo be technical only?

**Comment by oberstet** [comment]
We should move the docs markdown pages from the Wiki here to the crossbarwww repository (as regular files inside the repo).

**Comment by shaworth** [comment]
When working on security sensitive projects it is not uncommon to develop
(and occasionally deploy) in a 100% air-gaped environment.  Being able to
easily replicate documentation is a huge advantage.

**Comment by goeddea** [comment]
Moved the wiki content to crossbarwww repo.

**Comment by Vayel** [comment]
I don't see anything. Is it normal?

**Comment by goeddea** [comment]
Oops! Deployed the website, but forgot to push the repo. Is now there.
