### ISSUE TITLE
Pattern-based subscriptions and their authorisation configuration

### ISSUE THREAD

**Issue by deceze** [crossbario/crossbar#280]
I'm not entirely sure whether this is a bug or just lacking documentation: I can't get publications to work with pattern-based authorisation. Meaning, I am trying to publish to topics such as:

``` python
self.publish('foo.bar.baz.%s.something-happened' % baz.id)
```

With subscribers listening to:

``` python
self.subscribe(handler, 'foo.bar.baz..something-happened', SubscribeOptions('wildcard'))
```

This works fine, however I can't figure out whether the router supports limiting permissions for wildcard topics. E.g.:

``` yaml
- { uri: foo.bar.baz..something-happened, publish: true }
- { uri: foo.bar.baz..something-else-happened, subscribe: true }
```

This doesn't seem to work. `foo.bar.baz.*.something-happened` doesn't seem to work either. All publications are equally being rejected with `session not authorized to publish to ..`.

**Comment by oberstet** [comment]
Yes, wildcards in permissions configuration isn't implemented currently: https://github.com/crossbario/crossbar/blob/master/crossbar/router/role.py#L101

**Comment by deceze** [comment]
But it's coming, right? :o)

While I'm at it, may I ask for some clarification? Is the wildcard syntax explicitly looking for `..` as the placeholder? Or is this just a convention and some sort of longest-substring matching is applied? What if I was separating my event names like `foo-bar-baz` instead and wanted a `foo--baz` wildcard? Why not an explicit `foo.*.baz` wildcard syntax?

**Comment by oberstet** [comment]
WAMP specifies only 2 special characters for URIs: `.` and `#`. The latter is strictly for router internal use and must not appear within URIs. The `.` separates an URI into components. And URI components must not be empty - unless it is not an URI but a URI wildcard pattern.

Wildcard matching is based on matching components. And since empty components is disallowed in normal URIs, we use empty URI components to denote a wildcard component.

We could also use a dedicated, special wildcard symbol like `*` - but this then would need to be reserved (like `.` and `#`).

If you would like to see this, then we would first need to have that in the WAMP spec .. hence we needed an issue on the WAMP repo ..

**Comment by oberstet** [comment]
And yes, we want permissions to allow using URI patterns as well.

**Comment by deceze** [comment]
I see, thanks for the explanation. I'm perfectly fine with the `..` as wildcard syntax. It was unclear to me whether `.` was just a convention or had actual significance; now that you've clarified that it's an actual part of the WAMP spec that clears things up. :+1:

**Comment by eddieajau** [comment]
Is it possible to add dynamic authorisation into the scope of this issue?

I currently turn dynamic authorisation off because the RPC details only include the session ID, not the `authid`. So for every RPC call I need to fetch the session meta to get the `authid`. That's ok because I still end up with the same number of requests between Crossbar and my app.

But now I've come across a situation where I want to authorise a subscription, and that can only be done with a dynamic authoriser. So I can turn on dynamic authorisation, but for 99% of the calls to the router, this adds an unnecessary second call for every request. Ideally I'd like to use dynamic authorisation via a uri pattern, something like:

```json
{
  "name": "authenticated",
  "permissions": [
    {
      "uri": "*",
      "subscribe": true,
      "call": true
    },
    {
      "uri": "com.example.feed.*",
      "authorizer": "com.example.authoriseFeed"
    }
  ]
},
```

In this example, the intent is to give each user access to a notification feed in the form `com.example.feed.<authid>`, and I'd like to have a specific authoriser for that uri.

Does that sound reasonable?

**Comment by gregkeys** [comment]
+1

**Comment by Paranaix** [comment]
Definitely +1



https://github.com/crossbario/autobahn-python/issues/612 related?

**Comment by Kolyunya** [comment]
Upvoting for per-URI dynamic authorizers.

**Comment by meejah** [comment]
What should happen in crossbar if multiple patterns match? For example:

- `com..private` (match=wildcard)
- `com.something_specific.private` (match=exact)
- `com.` (match=prefix)

So then `com.something_specific.private` actually matches everything. Intuitively, it seems like "the most specific thing" should win (i.e. the match=exact). The less-clear case is between the wildcard and prefix matching. I would guess that mostly a matching "wildcard" should win over a matching "prefix"?

**Comment by meejah** [comment]
For the record, currently "the longest prefix" will win between match=exact and match=prefix (which sounds good to me).

What about this: if *any* wildcard URI matches, it wins. Otherwise, we take the longest-matching thing from the rest (i.e. current behavior). Possibly-better alternative: wildcard wins, unless there's a *strictly longer* match from the rest. (That is, in both cases the `com..private` thing above would be preferred).

**Comment by meejah** [comment]
In the above branch, I decided: "exact" matches always win. If a "wildcard" matches, it wins over any "prefix" match. So in the example a couple comments above:

- `com.something_specific.private` would match on the "exact" rule
- ...while `com.foo.private` would match on the "wildcard" rule 
- ...and `com.whatever` would match on the prefix rule.
- `foo.private` would match on nothing at all

**Comment by oberstet** [comment]
The original issue has been fixed long ago via above PR.

@markope as far as I understand, what you raise is different from this issue, but also available now: having `authid` available in the dynamic authenticator being called: that is also available for some time now (in the `session` dict provided in the 4 positional args `session, uri, action, options` when calling the user provided authenticator)

> fwiw, there is one more still outstanding roughly related issue: https://github.com/crossbario/crossbar/issues/261
