### ISSUE TITLE
Allow to set WAMP options via router configuration

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#283]
Allow to configure routers to disclose caller/publisher via configuration.

We could solve that like this:

```json
"roles": [
  {
     "name": "anonymous",
     "permissions": [
        {
           "uri": "*",
           "publish": true,
           "subscribe": true,
           "call": true,
           "register": true,
           "options": {
              "disclose_caller": true,
              "disclose_publisher": true
           }
        }
     ]
  }
]
```

**Comment by Paranaix** [comment]
I am a bit confused. Has not the `discloseCaller` option in the RegisterOptions message been removed from the standard, but now we try to implement a way to "hard-configure" it in the router? I am quite confused about the things that happened with the disclosing mechanisms.

IMO, a calle is the only one who ever has to specify whether peers should be disclosed or not, as he's the one who receives the information and has to work with it. While a caller might explicitely say that he doesn't want to get disclosed (but he has to expect an error then), I don't see the point of him being able to specify that he WANTS to be disclosed. Because whats the reasoning for this if the invoked calle can't work with that information. But if he can work with it, shouldn't he state on his own, that he expects his peers to be disclosed?

The proposed change just adds anothe element in this misery and creates a chaotic mess of configuration spread across 3 independent components IMO.

**Comment by oberstet** [comment]
@meejah @hawkowl do you have an opionion rgd the state of affairs rgd disclosing publisher/caller information in CB, AB and WAMP general? @Paranaix I'm afraid is right: it's a bit of a mess, and it seems the idea here doesn't make things better necessarily.

**Comment by meejah** [comment]
Thinking of this from an API-definition perspective, it makes the most sense that the publisher or callee decides if it *needs* the information or not. They can do this now, by checking ``if details.caller is None: its_an_error()`` of course, but maybe it makes more sense to have "demand_identity" or similar?

For symmetry it's maybe not a bad thing to leave the ``disclose_me`` in as well, but I'm struggling to think of a use-case where you'd want this to be optional? (That is, both an API that can deal with caller information or not *and* a client that cares to hide its session-id).

                                                 | ``caller.disclose_me = True`` |  ``caller.disclose_me = False`` 
------------------------------------------|------------------------------------------|---------------------------------------------
``callee.needs_session = True``  |  succeed                                 |  fail
``callee.needs_session = False`` | succeed                                  | succeed


(``.needs_session`` above could be a new option, or could just be an idiom like ``if not details.caller: error``). I'm guessing the idea here is that "semi-trusted" backends get less information about the calling peer...? What's a use-case where the backend can do something sensible without caller information and something different *with* caller information?

**Comment by deceze** [comment]
It appears to me that it is currently not possible to combine *dynamic authorisation* with router-level caller disclosure?! I don't see a reason why this couldn't work, but the current Crossbar implementation requires the replacement of the `permissions` dictionary key with the `authorizer` key; and since `disclose` is a child solely of `permissions`, it's only possible to choose one or the other.

That's rather... inconvenient.

**Comment by oberstet** [comment]
@deceze It's possible: simply returning `{"allow": true, "disclose": true}` from your custom authorized will do

**Comment by deceze** [comment]
@oberstet Awesome, undocumented easter eggs! :smiley:
Thanks!

**Comment by oberstet** [comment]
@deceze doc issue opened at https://github.com/crossbario/crossbardocs/issues/68
