### ISSUE TITLE
ApplicationSession.leave() results in unhandled exception

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#327]
Only tested in `onJoin()` but based on the error message I guess that this is a general problem:

    2015-05-16 15:19:35+0200 [Router 5760] exceptions.Exception: RouterApplicationSession.send:    unhandled message WAMP GOODBYE Message (message = None, reason = wamp.close.normal)

**Comment by meejah** [comment]
I can only repeat this with a component embedded in the router (not, for example, a component of a container).

It still makes sense to handle this appropriately. I guess this means you're done with that component? Or maybe it should mean to re-start the component? Or perhaps it should just be an error for a router-embedded component like this to try and disconnect, once joined?

To be clear, I can repeat this with a config like:

```
{
    "workers": [
        {
            "type": "router",
                      ...
            "components": [
                 "type": "class"
                      ...
             ]
        }
    ]
}
```

Note that because it's in the same process as the router, you'd have to re-start the router to reflect changes to .py files or similar (not just re-start the session).

**Comment by Paranaix** [comment]
Yes exactly, this happens in components directly embedded in the router. I haven't tested this in other scenarios. For how you want to handle this case, I don't know, but atleast there shouldn't be any uncaught exceptions. In our case we are currently calling leave() if we can't properly continue as intented, e.g if we can't register some callees.

**Comment by meejah** [comment]
@oberstet What is the desired behavior here? If you get a GOODBYE from any embedded router component, the whole router shuts down? (In the future it might be nice to add an option here; e.g. to be able to specify restart behavior).

(Also to be pedantic, this isn't really triggered by an unhandled exception, but because crossbar essentially just asserts if it gets a GOODBYE from any router component -- see https://github.com/crossbario/crossbar/blob/master/crossbar/router/session.py#L203).

**Comment by oberstet** [comment]
No, here is a proposal: the enclosing hosting router publishes an on component shutdown event. And then goes on. When a hosting router is itself shut down, it shuts down all embedding components which each will again lead to more events being published. When a router worker process has excited - for any reason, that is because of having been instructed to or because of panic - that's it. A CB node running from a local config essentially runs through the config once.

Am 23.08.2015 10:28 nachm. schrieb meejah <notifications@github.com>:

@oberstet<https://github.com/oberstet> What is the desired behavior here? If you get a GOODBYE from any embedded router component, the whole router shuts down? (In the future it might be nice to add an option here; e.g. to be able to specify restart behavior).

(Also to be pedantic, this isn't really triggered by an unhandled exception, but because crossbar essentially just asserts if it gets a GOODBYE from any router component -- see https://github.com/crossbario/crossbar/blob/master/crossbar/router/session.py#L203).

**Comment by oberstet** [comment]
ok, there are definitely issues left when running components side-by-side vs within containers: the commented case here fail https://github.com/crossbario/crossbarexamples/blob/master/containers/failures/Makefile#L16

**Comment by meejah** [comment]
Okay, so e.g. ``containers/failures/router/failure5/`` would publish something like ``crossbar.node.<node-id>.worker.<worker-id>.router.on_component_start`` with ``id=component1``, similar to container components? And then ``.router.on_component_stop`` when it leaves/exits.

This will need a bit more information passed down to the wrapping ``_RouterApplicationSession``, at least its ID and the worker-session (to publish events on) -- is stuffing these into the ``extra`` for the wrapped session config too ... obscure? (At this level worker/router.py:502, we don't actually create the _RouterApplicationSession directly -- it's implicit via the ``_router_session_factory.add()``)

Do you also want the recently added container behavior, whereby if the above happens *and* this is the last such component, the whole router shuts down as well? This is a bit less obvious to me than containers (which don't "do anything") whereas the router can still route if there are no embedded components.

**Comment by meejah** [comment]
From a Slack conversation, there are either "containers" or "routers" and a component can exit cleanly or uncleanly.

| container type | component exit status |  default behavior
| ------------------|-----------------------------|---------------------------------
| container        |  clean                         | if last, shutdown container
| container        |  fail                            | shutdown container
| router             |  clean                         | nothing
| router             |  fail                            | shutdown router

The "shutdown" could be controlled by an option, with this defaulting to shutdown when the last thing in a container exits (justification: the container doesn't do anything then) and defaulting to *not* shutdown for routers (justification: the router still does routing with no embedded components).

If there's a management uplink, the above shutdown behavior never happens. Also, the routers should publish "on_component_stop" events similar to the containers.

**Comment by oberstet** [comment]
Ah, that's a nice overview! We should add this to the docs in the end ...

Some more things (all for standalone mode):

* In the component failure exits, the container/router worker should shutdown and exit _with error_.
* For containers, when the last components exits cleanly, shutdown the container _with success_.
* If any worker exits with errors, shutdown the whole node with error - that is the controller exits with error
* If all workers have exited cleanly (with success), shutdown the whole node with success - that is the controller exits with error.
* When the controller process exits, either with sucess, error or just disappears, all workers should shutdown with error

**Comment by meejah** [comment]
So the original issue from @Paranaix is fixed in master at least, I am confirming the rest of the behavior specified in @oberstet's last comment.

**Comment by meejah** [comment]
Also, just to be clear, we *do* want to add ``on_component_stop`` and ``on_component_start`` events to workers running inside Routers, correct?

**Comment by meejah** [comment]
Just FYI, there will be some "non trivial" changes to make this happen; mostly in the router: it currently doesn't publish ``on_component_{start,stop}`` events at all, and doesn't (ever) shut down automatically.

For 0.12.0 perhaps it's best to put in a new ticket for the router-component behavior, and leave this issue as the ``assert`` that the original report mentions (that is fixed). I've put the table and description in the docs, and will confirm the behavior of containers.

**Comment by oberstet** [comment]
@meejah Just merged your latest PR rgd this. The original issue (and more) is now fixed. For the "bigger picture", I submitted a new issue https://github.com/crossbario/crossbar/issues/615

**Comment by meejah** [comment]
looks like i forgot to push the docs changes, which are here: https://github.com/crossbario/crossbarwww/pull/87

(not sure why it says it can't merge; it seems based on top of master from my end :/ )
