### ISSUE TITLE
change conf.json to crossbar_conf.json

### ISSUE THREAD

**Issue by markope** [crossbario/crossbar#330]
Just a little thing:

if you have a conf.jon file in your development folders, that doesn't tell you much. A name like ```crossbar_conf.json``` would be helpful for that. (Maybe as optional name for the conf.json.)

**Comment by meejah** [comment]
crossbar really has the concept of "a directory" that it controls, which can be specified with `--cbdir X` -- I guess at least partially because it writes a `node.pid` file in there as well when it's running? Also things like UNIX socket files, TLS certificates go in this directory. It's the default root for Web content as well if you supply relative paths in your config.

So you could I suppose have a `crossbar_router/` sort of thing in your dev folders, with `config.json` and any other things required for crossbar configuration.

**Comment by oberstet** [comment]
@meejah is right, the config lives in the `.crossbar` node directory, and CB does what it likes in there (user are not supposed to fiddle/touch that). We need an area under CB control ...

**Comment by markope** [comment]
Sure, I could put it in a folder with a name as @meejah suggested. It is just about naming conventions. 
Nevermind. As I said it is just a little thing.
