### ISSUE TITLE
RawSocket ping/pong messages

### ISSUE THREAD

**Issue by darkl** [crossbario/crossbar#381]
I'm working a RawSocket client implementation for WampSharp.
Everything went well until I introduced the ping/pong messages. When I send a crossbar router a ping message, it drops the connection.
By looking at the code (in this repository and AutobahnPython, and AutobahnCpp repositories), I couldn't find anything related to ping/pong messages.

It seems that crossbar and Autobahn variants don't implement the RawSocket ping/pong spec.
I'll make this configurable so that WampSharp can choose not to auto-ping routers, but I'm opening this issue for your attention.

Thanks

**Comment by tlausch** [comment]
That i noticed too. Crossbar rawsocket missinterprets all bits including the ping pong reserved bits as message length. It drops the connection since the ping pong bits make the message seem larger than allowed.

As far as i know ping pong is a Feature of websocket and not necessarily needed for a raw Connection. 
Is there any benefit of implementing ping pong on a raw socket at all?

Greetings

----- Ursprüngliche Nachricht -----
Von: "Elad Zelingher" <notifications@github.com>
Gesendet: ‎01.‎08.‎2015 00:31
An: "crossbario/crossbar" <crossbar@noreply.github.com>
Betreff: [crossbar] RawSocket ping/pong messages (#381)

I'm working a RawSocket client implementation for WampSharp.
Everything went well until I introduced the ping/pong message. When I send a crossbar router a ping message, it drops the connection.
By looking at the code (in this repository and AutobahnPython, and AutobahnCpp repositories), I couldn't find anything related to ping/pong messages.
It seems that crossbar and Autobahn variants don't implement the RawSocket ping/pong spec.
I'll make this configurable so that WampSharp can choose not to auto-ping routers, but I'm opening this issue for your attention.
Thanks

**Comment by darkl** [comment]
Ping/Pongs are part of the [RawSocket spec](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#rawsocket-transport), they are useful for detecting connection loss (in cases where a FIN packet hasn't been sent, for example on violent disconnections, such as disconnecting network cable).

**Comment by oberstet** [comment]
@darkl correct: the spec has ping/pongs defined for RawSocket, but AutobahnPython and Crossbar.io currently lack this

see also: https://github.com/tavendo/AutobahnPython/issues/453

**Comment by fhriley** [comment]
> Crossbar rawsocket missinterprets all bits including the ping pong reserved bits as message length. It drops the connection since the ping pong bits make the message seem larger than allowed.

I filed #1206 for this, but it was closed.

**Comment by oberstet** [comment]
@noisyboiler _WebSocket_ ping/pongs should work perfectly on crossbar. in fact, I would dare to claim that crossbar / autobahn-python has one of the most sophisticated (read: controllable) implementations of websocket heartbeating. it is non-trivial to make this fly when you have large numbers of connections.

ping/pong/hearbeating on _RawSocket_: this is what we are missing implementation wise ..

**Comment by noisyboiler** [comment]
@oberstet 
yeah, it works perfectly, thanks, and haven given it some consideration over the past days I've realised it is indeed non trivial! I'll take a look at how you guys do it out of interest.
Many thanks.

**Comment by oberstet** [comment]
this needs to be fixed in Autobahn https://github.com/crossbario/autobahn-python/issues/453, hence closing the issue here
