### ISSUE TITLE
REST bridge: UTF8 handling and checking

### ISSUE THREAD

**Issue by ParkhomenkoDmitro** [crossbario/crossbar#389]
When I sent post request with body that contains not ascll characters I get next error:
400 / invalid request event - HTTP/POST body must be valid JSON: 'ascii' codec c
an't decode byte 0xd0 in position 107: ordinal not in range(128)
What can lead to this problem? and how to solve it?

**Comment by shaworth** [comment]
What leads to this problem is one or more bytes which are outside of the
ASCII character set.  In this case the error message is explicit, the
character at position 107 has a hex value of 0xd0.  To fix this you need to
either encode the data using something like base64 (
https://www.base64encode.org/) or remove the problematic data.  Given that
the 0xd0 appears to be a cryillic character, your best bet is to encode the
data during transmission and decode it upon receipt.

**Comment by oberstet** [comment]
The POST body is decoded assuming UTF8: https://github.com/crossbario/crossbar/blob/master/crossbar/adapter/rest/common.py#L249

The `Content-Type` header is checked for `application/json` https://github.com/crossbario/crossbar/blob/master/crossbar/adapter/rest/common.py#L117, but not for being UTF8 encoded.

The correct behavior for a client is:

* encode the POST body in UTF8
* set the `Content-Type` header to `Content-Type: application/json;charset=utf-8`

The bug in Crossbar.io hence is:

* not checking the request header for `charset=utf8`
* not giving a proper error response when the former isn't set
* not giving a proper error response when the former is set, but the body isn't valid UTF8

Note: we should check the header, _and_ check the body for valid UTF8 using AutobahnPython's 100% strict UTF8 checker (https://github.com/tavendo/AutobahnPython/blob/master/autobahn/websocket/utf8validator.py) instead of relying on `json.loads` doing the right thing.

**Comment by oberstet** [comment]
This should also be documented http://crossbar.io/docs/HTTP-Bridge-Services-Publisher/#making-requests

**Comment by hawkowl** [comment]
I'll take point on this.

**Comment by hawkowl** [comment]
#391 ought to fix this up.

**Comment by oberstet** [comment]
fixed in trunk
