### ISSUE TITLE
How do I get a list of topics I can subscribe to?

### ISSUE THREAD

**Issue by mfojtak** [crossbario/crossbar#396]
I am new to WAMP and still trying to get my head around this.

I cannot find anywhere in the docs a way how to get a list of topics/events I can subscribe to.

Let say I want to implement a news server and make it WAMP-friendly. I would assume that the server would be publishing articles. The user would then subscribe to the router.

However, how does a user get a list of news publishers that are registered to the central router?

Ironically, I can use wamp.registration.lookup to get a list of the news readers. But no way to get the actual news.

Is there a plan to implement topic/event metainfo api?

**Comment by goeddea** [comment]
Publishers do not need to register a topic - so there is no list of topics as such.

What does exist is a list of subscriptions (since these, logically, need to be registered). You can retrieve this list via a meta-procedure (see http://crossbar.io/docs/Subscription-Meta-Events-and-Procedures/). The list of subscriptions gives you the topics to which there currently are subscribers - but not all topics which may exist. (Additionally, there may be topics which are currently only covered by prefix/wildcard subscriptions, so you may not event get the full topics here.)

Getting a list of a available topics for subscriptions (like in your news reader example) thus has to be an application-level feature. You can have a component which provides this to the client on request.
