### ISSUE TITLE
Logging should use unbuffered output

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#506]
When running Crossbar under systemd, log output doesn't appear because of buffering.

Adding `-u` to the `crossbar` script installed works, but
- requires patching the installed script
- not sure about side-effects (we only want unbuffered output for the node controller logging)

``` python
#!/opt/crossbar/bin/pypy -u

# -*- coding: utf-8 -*-
import re
import sys

from crossbar.controller.cli import run

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
```

**Comment by meejah** [comment]
You can also set the ``PYTHONUNBUFFERED`` environment variable. https://docs.python.org/2/using/cmdline.html#envvar-PYTHONUNBUFFERED

Related: it might be nice to include this option (e.g. via env-var) when starting guests, as it's a not-uncommon source of problems for Python guests. Probably with some flag to turn it off, I suppose... :/

**Comment by oberstet** [comment]
Ah `PYTHONUNBUFFERED` .. yeah. I'll use that in systemd service definitions. So it's more a doc issue. That env var can also be set for guests. Also needs docs.

**Comment by meejah** [comment]
Personally, I think we should set it for guests always, ourselves *unless* they have specified it in their environment via the options -- if only to cut down on bug reports ;) (as often for short "test" programs that don't ever produce a lot of output, you see nothing)

**Comment by oberstet** [comment]
> I think we should set it for guests alway

Agreed. Makes sense.

**Comment by meejah** [comment]
Although PR #641 solves this for guests/worker processes, it doesn't actually do what the original bug is wanting: unbuffered output for the main process. This actually proves harder than I thought:

 - there doesn't seem to be a way to get setuptools to make a script containing ``-u``
 - I can't find a way to get environment-variables set in the generated script
 - stack-overflow suggests various hacks to re-open or ``fcntl`` stdout ...

I didn't explore the final approach too far...

Another option is to make the 'crossbar' module runnable, so that there's an alternative way to "make it go" and pass ``-u``: ``python -u -m crossbar``. This would involve making a ``crossbar/__main__.py`` which basically just does the same thing as the generated script, or just invokes ``crossbar.controller.cli.run``. So maybe just a documentation thing?

(You can try this right now with ``python -u -m crossbar.controller.cli`` actually...)

**Comment by oberstet** [comment]
Thanks for digging! This is unfortunate.

`python -u -m crossbar.controller.cli`: works of course, but isn't a nice UX. Keeping a `crossbar` command to invoke should be retained.

Hacking via `fcntl` seems .. a hack. With unclear side effects.

Maybe this? http://stackoverflow.com/a/17329493/884770

**Comment by oberstet** [comment]
I have fallen into this trap myself more than once (even though I know about the thing), and it sucks. Hence bumping to bug level.

The above SO answer seems promising ..
