### ISSUE TITLE
Handle signals systematically

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#556]
We should handle signals (TERM, ...) systematically for node controller and workers processes.

For background and as an example, here is what the PostgreSQL guys do (likely more sophisticated than we want right now for Crossbar.io, but anyway):

> If at all possible, do not use SIGKILL to kill the main postgres server. Doing so will prevent postgres from freeing the system resources (e.g., shared memory and semaphores) that it holds before terminating. This might cause problems for starting a fresh postgres run.
> 
> To terminate the postgres server normally, the signals SIGTERM, SIGINT, or SIGQUIT can be used. The first will wait for all clients to terminate before quitting, the second will forcefully disconnect all clients, and the third will quit immediately without proper shutdown, resulting in a recovery run during restart.
> 
> The SIGHUP signal will reload the server configuration files. It is also possible to send SIGHUP to an individual server process, but that is usually not sensible.
> 
> To cancel a running query, send the SIGINT signal to the process running that command. To terminate a backend process cleanly, send SIGTERM to that process. See also pg_cancel_backend and pg_terminate_backend in Section 9.26.2 for the SQL-callable equivalents of these two actions.
> 
> The postgres server uses SIGQUIT to tell subordinate server processes to terminate without normal cleanup. This signal should not be used by users. It is also unwise to send SIGKILL to a server process — the main postgres process will interpret this as a crash and will force all the sibling processes to quit as part of its standard crash-recovery procedure.

Desired behavior for Crossbar.io:
1. when the node controller process is killed with SIGKILL, all workers processes automatically exit. In this case, no management API event is (and can be) published.
2. when the node controller processes is sent a SIGTERM, it will start an orderly shutdown of all currently running workers and finally of itself. In the course of the shutdown, management API events are published.
3. when a node worker process is killed with SIGKILL, the node controller will catch this unclean exit, log a warning level message and publish a management API event
4. when a native worker process is sent a SIGTERM (which can be done directly, or from the controller via management API), the native worker will do an orderly, clean shutdown and finally exit cleanly. the node controller will cach this clean exit, log a info level message and publish a management API event

**Comment by meejah** [comment]
I *believe* the SIGTERM handling mostly works like that.

When shutting down worker processes, the node-controller does a TERM and then, after a timeout, does a KILL (this is hard-coded at 20s: https://github.com/crossbario/crossbar/blob/3aae93065805e8a29a8abffe32c957a9e2851760/crossbar/controller/process.py#L646) and that one even has a unit-test ;) https://github.com/crossbario/crossbar/blob/0fbdfa6434e107ea8ece54a2d6e6df738c5f4c36/crossbar/controller/test/test_cleanup.py#L51

Arguably, it might be better to simply wait forever...?

The thing that probably *doesn't* work is that we should be doing things in the correct order in order to get a maximum number of events out: the router-worker(s) should be shut down last. However, this is probably best orchestrated via the management uplink which can shut down everything via WAMP API calls and then tell the node itself to shutdown (last) when only router-worker(s) are running. I think?

There are also several test-cases in CTS regarding SIGINT handling of workers/guests.

**Comment by oberstet** [comment]
I've added the stuff missing: worker shutdown (https://github.com/crossbario/crossbar/commit/39ccdb78faed9b0b52b4276e2349a96369a53697) and TERM handling (https://github.com/crossbario/crossbar/commit/3116a2110f8218d345ca429cb45eecc59780a4c5) and management events (https://github.com/crossbario/crossbar/commit/a392ae4f9fdb91a45a5120f9be51f2abdf46c227). There is still some bits missing though .. working on this.

When the node runs in "standalone mode", the order of shutdown doesn't really matter, since there is no uplink to receive the management events anyway. And when the node runs in "managed mode", only the uplink management app will trigger (and orchestrate) orderly shutdowns.

**Comment by oberstet** [comment]
we have 4 cconfigurable shutdown modes (for longer time now): https://github.com/crossbario/crossbar/blob/master/crossbar/common/checkconfig.py#L67

this allows flexible control of behavior under the described conditions
