### ISSUE TITLE
No color with logging for "crossbar version"

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#600]
A minor thing, but I am wondering why `crossbar version` doesn't do colored output, while `crossbar start` does.

**Comment by hawkowl** [comment]
I've figured out why -- `crossbar start` has the "colour" log format by default, while all other commands have "none" (so that the timestamp does not show, but it still works through the regular logging interface rather than having two approaches to doing text output).

The proper solution to this is to do what is said here http://stackoverflow.com/questions/1077113/how-do-i-detect-whether-sys-stdout-is-attached-to-terminal-or-not and make colour a "is tty" thing, rather than a "what is the logging timestamp format" thing (with overrides/manual settings of course). This'd also cover the instance where you run Crossbar as `crossbar version > versiondetails.txt` -- `isatty()` would return False, so it wouldn't write terminal-colouring ANSI garbage to the file by default.

This is super simple to implement with how it's architected currently, so I can fix this up.

**Comment by oberstet** [comment]
Ahh. Ok;) I knew you'd figure it out quickly;)

**Comment by hawkowl** [comment]
PR submitted at #609
