### ISSUE TITLE
source (.py) needed at runtime (.pyc are not enough)

### ISSUE THREAD

**Issue by mcondarelli** [crossbario/crossbar#622]
I am trying to prepare a "minimal set" installation (Buildroot).
It seems *sources* for /build/lib/crossbar/worker/worker.py and build/lib/crossbar/worker/process.py are needed at runtime. The corresponding worker.pyc and process.pyc are not enough.
Why is it so?
Unless I (manually) copy the files to target it bombs with "file not found" error.
What am I doing wrong?

**Comment by meejah** [comment]
In general, trying to not-ship .py files with Python tends to be "hard"...but can you post more details? At least process.py is invoked in a subprocess when running workers (e.g. in controller/process.py). However, worker.py isn't, so I'm not sure why that's apparently required.

However, .pyc files are basically just a cached version of the compiled .py file so I'm not convinced of the wisdom of not simply shipping the .py files, especially since crossbar is open-source anyway.

**Comment by oberstet** [comment]
@mcondarelli regarding your question, yes, as @meejah notes, these are required to start (native) worker processes.
