### ISSUE TITLE
Programmatic way (/Interface) to start router

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#655]
We solely use Autobahn and Crossbar for our application. Im currently looking for a way to make our wamp interface as a whole, consisting of endpoints and topics and such, testable. For this I require a router of course. I must also be able to set up crossbar specific stuff like authorizers and authenticators.

Before the router code was seperated into Crossbar, it was possible, to start a router in a simple programmatic way using Autobahn. I'm looking for a simple, preferably top-level, interface to setup a router. Does such an interface already exists. If so, what assertions are made about stability (/backward compatibility)?

I'm aware of crossbars "blackbox" paradigma. If possible I don't want to start an extenal binary, prepare cli arguments, rely on config files on my disk and monitor a process so that my tests can run. My application is written specifically with crossbar in mind, as such, there has to be a simple way to test it as well.

**Comment by meejah** [comment]
The way I have run "integration" or such high-level tests with crossbar is to start up a crossbar instance in a temporary directory. Using py.test (with a ``@fixture`` for crossbar) for this works quite well, in my opinion, and I can start up several variant crossbar instances this way.

Honestly, I don't see why it's any more "onerous" to have a spawn-process line instead of calling a Python function -- even with a "Python function to call" way, you'd still need to pass configuration to crossbar (presumably via a dict instead of first calling ``json.dump()`` on the very same dict). It is *slightly* more complicated, but if I were to implement your feature-request as it is stated above, that's literally all it would do. Perhaps this precisely what you're asking for ...?

Can you outline your use-case(s) that are cumbersome to test while treating crossbar as any other daemon ...?

For more unit-test style tests of individual components, I wouldn't use a router at all -- I would simply call the functions (e.g. invoke RPC endpoints directly, etc).

**Comment by oberstet** [comment]
>  Does such an interface already exists.

There isn't, and there won't be.
