### ISSUE TITLE
Cleanup of cookie storage file

### ISSUE THREAD

**Issue by taueres** [crossbario/crossbar#662]
Unfortunately the cookie file used by Crossbar for authentication tracking is opened in "append mode". This file is going to increase its size without limit even after Crossbar restart.

I wrote a simple Crossbar subcommand `clean-cookies` for removing useless and outdated cookie entries.

You can find it here: https://github.com/taueres/crossbar/commit/21955d110e5f301bec7d515d8b623fb19ae506e5

What do you think?
Is there any improvement I could do?
Do you have other solutions?

**Comment by oberstet** [comment]
Thanks for filing an issue .. and providing code. Shows you really care;)

Now, thing is: Crossbar.io not only can start from a static config, but also be configured dynamically (via API .. not yet officially released).

Because of this, a better place for purging code would be `CookieStoreFileBacked.__init__`. And to activate, have a new config option on the cookiestore (of type file): **purge_on_startup = True|False** (with default False).

> Note: the cookie file store backend is only a first quick backend. We will have an LMDB backend that will be recommended then for production use. That won't have this issue anyway as LMDB is a "proper database" and allows to transactionally update existing records.

**Comment by taueres** [comment]
Thanks @oberset for the tips. I'm working on a patch. PR will follow shortly.

**Comment by taueres** [comment]
@oberstet I've just opened a new PR https://github.com/crossbario/crossbar/pull/670

**Comment by taueres** [comment]
@oberstet I think you can close this issue now. Thanks.
