### ISSUE TITLE
Packaging crossbar for Debian

### ISSUE THREAD

**Issue by oorestisime** [crossbario/crossbar#846]
Hello folks,

Thanks for the awesome tool you provide.
I am trying to package crossbar for Debian and i am wondering if there's a reason you omit docs from the pypi package. It would be great if they were in so i could provide a crossbar-doc package with the documentation in it.

And a small question. In the pypi package in the templates/hello/{erland,java,csharp} there's a .gitignore. is this really needed by the package when it is installed/used? If not then it might be better to avoid adding them.

Cheers,
Orestis

**Comment by meejah** [comment]
Hi @oorestisime 

When you say "the docs", do you mean the markdown sources, or the html-rendered result, or ..?

As to the `.gitignore`, is this maybe a consequence of `include_package_data=True`? I don't know why they're being included, and obviously won't be useful from a tarball anyway.

**Comment by oberstet** [comment]
Hey, hi!

* The docs are not included in the pypi package because they need to be "built", and really are only user readable when rendered from the web infrastructure on our web site. Users should be better be pointed to http://crossbar.io/docs/.

* The .gitignore's are there as a convenience for people instantiating directly into a Git repo, where you then don't want to push all the build artefacts when doing an in-source build.

So yes, we would like to preserve both things.

On a sidenote, you probably should not package up Crossbar.io in distro packages:

* for one, packaging Python packages in distro packages sucks big time .. it will install into system wide locations, which is wrong, because it should be done using virtualenv
* then, we have our own binary package builds for Crossbar.io  http://crossbar.io/docs/Installation-on-Ubuntu-and-Debian/
* then, we have Docker images for Crossbar.io, also provided by us

Distro packages suck. Yes, I know this is a controversial opinion. And I basically don't care;)
