### ISSUE TITLE
MQTT: topic/URI mapping

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#884]
This should be done canonically (that is, without knobs or stuff).

Because the hierarchical delimiter in MQTT "/" can be directly mapped to "." in WAMP.

"#" designed a prefix pattern based subscription.

Same with wildcards "+"

What we do currently lack is ability to mix wildcard/prefix

Rgd  $SYS/: we could map that to WAMP/CB meta API ("wamp._", "crossbar._")

**Comment by oberstet** [comment]
MQTT topic names in MQTT PUBLISH messages received from MQTT clients should be checked using using our own UTF8Validator

Also: handle the case of WAMP URIs >64k. MQTT topic names must have a UTF-8 encoding length of maximum 65535 octets. We cannot forward that. Likely, we need to throw away the event (the event can only be dispatched to WAMP clients, not MQTT clients), but maybe log that with a WARNING.

**Comment by hawkowl** [comment]
Just an aside -- *all* UTF-8 strings read out of MQTT packets are validated with `Utf8Validator`.

**Comment by hawkowl** [comment]
Oooh, here's some problems from 4.7.3 Topic semantic and usage:

- Topic Names and Topic Filters are case sensitive
- Topic Names and Topic Filters can include the space character
- A leading or trailing ‘/’ creates a distinct Topic Name or Topic Filter
- A Topic Name or Topic Filter consisting only of the ‘/’ character is valid 

I don't believe we can map these directly to WAMP URIs, since URIs are case-insensitive. Also, WAMP doesn't let you have a single "." as a topic name...

**Comment by hawkowl** [comment]
Okay, potential idea. This might screw with https://github.com/crossbario/crossbar/issues/885 but I'm just throwing things out there, as this is a hard spec compliance thing...

So, we have a number of problems mapping MQTT to WAMP, of which the two biggest are:

- the payload
- the topic

If we are to make it drop-in, then we need to make both map identically to WAMP. That is, the use case that someone has a MQTT library and wants to connect it to Crossbar, and have it act (mostly) like a WAMP client would, but just using MQTT. In this case, we can allow a non-spec-compliant, but theoretically possible canonicalisation -- the payload is a JSON encoded UTF-8 string, and the topic is directly mappable to WAMP URIs (that is, all lowercase, no mixing prefix and wildcards).

The other use case is that you have an existing MQTT client, or MQTT broker, that you want to replace with Crossbar (possibly as part of a WAMP transition, or operating side-by-side, if you can't replace the MQTT-speaking devices). Here, it's *likely* that the topic is able to be directly mappable, but it is also *possible* that it won't be. It's also possible that the payload might be JSON, but it's also possible it's binary trash. In this case, we can't provide a drop-in solution -- because we can't directly map the topic, and MQTT requires some extra metadata to be associated with the message which WAMP does not provide (for example, the QoS value transits through points, and the max QoS is done by subscription). We can normalise the mapping down (removing things that make it an invalid URI) for sending to WAMP clients, but we still need to maintain the mapping for MQTT clients. That is, if `foo/bar/baz` and `Foo/Bar/Baz` are both normalised to `foo.bar.baz` on the WAMP side, we CANNOT let a MQTT client that subscribes to `Foo/Bar/Baz` get subscriptions for `foo/bar/baz`. Therefore, we could allow some form of normalisation for the WAMP side, but somehow attach the *original*, non-normalised MQTT topic to the publishes and events, for WAMP clients to distinguish between `Foo` and `foo`, and for the MQTT adapter to only forward messages that match the exact subscription (since the MQTT adapter would have to use the WAMP normalised topic name for subscribe/publish). I'm not sure how to do this, exactly -- the closest I have got is thinking about args/kwargs that look like `[u"<base64 encoded binary payload>"], {u"mqtt_qos": 0, u"mqtt_topic": u"foo/bar/baz"}`. This would then be encoded as usual, but without using opaque payload -- as you can't have both an opaque payload and args/kwargs. Plus, I don't think most clients other than the Python one support opaque payloads, and I see JavaScript, Autobahn or not, being a big use case for this (connecting MQTT to the web browser via WAMP). So I'm wondering if we don't use opaque, at least initially, and have essentially two options:

- An option where the MQTT client and what it sends is completely controlled by whoeever is setting up the MQTT adapter and can ensure no mapping or payload issues occur, and do not mind about the QoS being non-transiting (this might cause problems between MQTT clients... since if a QoS 1 publish is sent over a QoS 2 subscribe, it should be QoS1, not 2... so we can't send all messages as the max-QoS that the client requests). This is the "drop in" scenario.
- An option where the MQTT client cannot be modified, which sends it in the payload-in-args-and-metadata-in-kwargs. In this example, the WAMP client would have to be completely controlled by whoever was deploying Crossbar, as their subscribers would have to handle this data format. Publishes on the WAMP side with `mqtt_topic` might have to then be sent on that topic in the adapter (checking that it normalises down, first). This is the "side by side" scenario.

What do you think, @oberstet ? I can't think of an easy solution to this, considering the different approaches MQTT and WAMP take to topics and payloads. The decision here also affects the will topic -- as a Will for `foo/bar` and `Foo/Bar` will be for `foo.bar` in WAMP, but MQTT clients will expect them to be separate... Of course, the other solution may be to allow case-insensitive WAMP URIs,  but then it's not a URI, and I feel like that would be a massive footgun for older clients who now can't subscribe to a whole range of topics...

**Comment by BrechtDeVlieger** [comment]
Is there any update on the prefix and wildcards? This is an important feature for our project.

**Comment by oberstet** [comment]
rgd

> WAMP URIs, since URIs are case-insensitive.

No, WAMP URIs are case-sensitive.

> Is there any update on the prefix and wildcards? 

It is not implemented yet, and given our current backlog, can't say when we get to it. If you are using this in a commercial context, we might be able to arrange things quicker (and then pls get in touch with me via email).

**Comment by oberstet** [comment]
MQTT prefix/wildcard subs are now properly mapped to WAMP - here is a complete example https://github.com/crossbario/crossbar-examples/tree/master/mqtt/patternsub
