### ISSUE TITLE
HTTP Bridge: dynamic auth

### ISSUE THREAD

**Issue by meejah** [crossbario/crossbar#936]
It would be useful to be able to do dynamic authentication when using the various HTTP-Bridge things. Currently, a realm + role is assigned from the static configuration for that bridge endpoint.

It would be most-useful if the dynamic authenticator got information about the real underlying request (e.g. all the headers) so it can base decisions on Web basic-auth and/or "real" IP (e.g. if `X-Real-IP` header is sent because you're behind nginx or other reverse proxy)

**Comment by oberstet** [comment]
.. from IRC: the REST bridge has access to the service session of the router, and can use that to call into your dyn. auth instead of looking into the static config object

**Comment by matthewh** [comment]
Hello @oberstet, this issue just became an issue for me that I need to solve. Does your comment indicate its working or suggest a way to implement it?

**Comment by oberstet** [comment]
This is a suggestion how to implement. It is easy .. the machinery is there .. just needs to be hooked up.

**Comment by matthewh** [comment]
@oberstet Would you be open to a pull request for this feature?

How do you feel about a custom WWW-Authenticate header to allow WAMP-CRA over the HTTP bridge?

**Comment by oberstet** [comment]
@matthewh Contributions are definitely welcome! Please see the contributions notes [here](https://github.com/crossbario/crossbar/blob/master/CONTRIBUTING.md#contributing-code).

Right now, the only way to add authentication to the bridge is by providing a static key/secret (http://crossbar.io/docs/HTTP-Bridge-Publisher/#configuration). This works at the _payload_ level (that is, the stuff the client HTTP/POSTs in the request body must contain a simple signature that derives from the content being POSTed and the key/secret).

The issue here was mainly to allow to configure a dynamic authenticator like WAMP procedure that dynamically provides key/secret).

That being said, at the HTTP transport level, we could additionally add:

* TLS client cert based auth
* HTTP cookie based auth

Both of these could in turn work statically (via config.json static configuration), or dynamically eg see these examples

* https://github.com/crossbario/crossbar-examples/tree/master/authentication/tls/dynamic
* https://github.com/crossbario/crossbar-examples/tree/master/authentication/cookie

--

HTTP also allows for "basic auth" and "digest auth" by the standard. I don't know if it's worth, but these could be made working too. Again, both in static and dynamic flavors.

I don't see how we would get WAMP-CRA into the mix, because WAMP-CRA is a challenge response scheme (more sophisticated than HTTP "digest auth"), which requires 2 round trips.

--

Personally, I'd be most interested dynamic TLS client cert based auth, as this does away with any kind of shared secret.

I am open to discuss / expand in this feature area. My main concern is: it should feel natural (fit into the general config / API design).

@meejah opinions?

**Comment by matthewh** [comment]
Thanks for the detailed description @oberstet!
I believe I have a straight-forward approach to making WAMP-CRA work over the HTTP bridge with a custom WWW-Authenticate header (or 2) but I'm willing to table that until I have a handle on everything you mentioned.

**Comment by meejah** [comment]
IIRC, this was originally a request from someone wanting to do dynamic-auth based on the IP addresses of clients (but they were behind nginx so needed header access). I agree that WAMP-CRA might be hard, because of the round-trips...but if @matthewh has a way, I'd be interested to take a look :)

Probably a general dynamic-auth hook that gets called would be nice. The question becoming "what information does it get" -- i.e. *all* headers? Some filtered list of headers? Some list of headers from the config? Other information? How do you see a challenge-response working over HTTP though?

**Comment by matthewh** [comment]
@meejah  Starting from the RFC for HTTP basic authentication, see https://tools.ietf.org/html/rfc2617#section-2, I'd extend the challenge WWW-Authenticate header to include all of the necessary information needed for the client to generate the signature and place it in the next request http header **Authorization: Wampcra**. One major difference with wamp-cra is that the server will need the authid in order to return the appropriate information.

### Assuming the client does not know the salt, iteration, and keylen in advance.
1. An HTTP request with no Authentication information gets an HTTP 401 with header WWW-Authenticate: Wampcra realm="<crossbar bridge realm name>"
2. An HTTP request with header **Authentication: wampcra authid=peter** get an HTTP 401 response  with header *WWW-Authenticate: salt=salt123 iterations=100 keylen=32 etc...*
3. Next, client issues HTTP request with header **Authentication: wampcra <signature>** and a valid signature gets the call properly executed and a value returned.

### Once the salt, iteration, and keylen are known
1. Next, client issues HTTP request with header **Authentication: wampcra <signature>** and a valid signature gets the call properly executed and a value returned.

### Notes
* My dynamic wamp-cra authenticator always returns randomized values for salt, iterations, keylen, etc if the authid is unknown. I feel this is important to prevent user account enumeration.

**Comment by matthewh** [comment]
First attempt at implementing WAMP-Ticket authentication with HTTP Basic Authentication. The credentials can also be specified as GET parameters (unsure if useful/desired). HTTP headers are passed through as requested.

I'm hoping you can take a moment and provide some guidance/pointers. I don't expect this PR to land as is.  I still need to provide tests and docs.
