### ISSUE TITLE
error message on cookie auth

### ISSUE THREAD

**Issue by markope** [crossbario/crossbar#952]
Setup:
autobahn-js 9.9 in Front End no cookies on page
crossbar 16.10.1 in back end with no cookie store file in .crossbar folder

Issue:
My autobahn-js front end tries to authenticate with a cookie at the crossbar router. 
I get

2017-01-13T20:38:29+0100 [Router      79691] Traceback (most recent call last):
2017-01-13T20:38:29+0100 [Router      79691]   File "/usr/local/lib/python2.7/site-packages/crossbar-16.10.1-py2.7.egg/crossbar/router/protocol.py", line 240, in onConnect
2017-01-13T20:38:29+0100 [Router      79691]     self._authid, self._authrole, self._authmethod, self._authrealm = self.factory._cookiestore.getAuth(self._cbtid)
2017-01-13T20:38:29+0100 [Router      79691] ValueError: too many values to unpack

I looked at the code but have no idea what this could be....

**Comment by markope** [comment]
the cookie.dat get's filled up with entries like this forever:

    {"authrealm": null, "max_age": 604800, "authmethod": null, "authextra": null, "created": "2017-01-13T19:51:04.775Z", "authrole": null, "authid": null, "id": "jrOufMXR1dPDp8gIINETyiDc"}

**Comment by CuCTeMeH** [comment]
They need to fix it. I found the issue. They updated the cookiestore but not updated the protocol that uses it.


Basically in the cookiestore the cookie contains one extra param called 'authextra' here from their code:

            # when a cookie has been set, and the WAMP session
            # was successfully authenticated thereafter, the latter
            # auth info is store here
            'authid': None,
            'authrole': None,
            'authrealm': None,
            'authmethod': None,
            'authextra': None,

But the protocol.py on the def onConnect method (row 240 in version 17.2.1 latest for now) that gets the auth from cookiestore gets only 4, so the unpack function throws an error. The basic fix I can do is this:
                    self._authid, self._authrole, self._authmethod, self._authrealm = self.factory._cookiestore.getAuth(self._cbtid)

This should look like this:
                    self._authid, self._authrole, self._authmethod, self._authrealm, self._extra = self.factory._cookiestore.getAuth(self._cbtid)

This is a really quick workaround because below the code somewhere must use this extra parameter if you need to pass some extra stuff (this is optional however but...). If you dont need to pass some extra stuff this quick fix will do the job for you :)

**Comment by oberstet** [comment]
fixed on master
